/* Generated by scripts/build-glossary.py from topics/glossary.html. Do not edit. */
window.HSC_GLOSSARY = [
{
"id": "term-cloud-computing",
"name": "Cloud Computing",
"aliases": [
"Cloud Computing"
],
"def": "Delivering computing services such as storage, servers, databases and software over the internet, so an enterprise rents capacity instead of owning and running all of its own hardware.",
"example": "A small business keeps its files in a cloud drive and pays each month for exactly the storage it uses.",
"link": true
},
{
"id": "term-enterprise",
"name": "Enterprise",
"aliases": [
"Enterprise"
],
"def": "An organisation, such as a business, school, charity or government agency, that uses computing systems to achieve its goals.",
"example": "A local bakery that takes online orders and tracks its stock in a spreadsheet.",
"link": false
},
{
"id": "term-user-experience",
"name": "User Experience (UX)",
"aliases": [
"UX",
"User Experience"
],
"def": "The overall experience a person has when using a system: how easy it is to learn, how efficiently they can complete tasks and how they feel about it.",
"example": "A checkout that takes three taps instead of ten.",
"link": true
}
];
