/* Generated by scripts/build-glossary.py from topics/glossary.html. Do not edit. */
window.HSC_GLOSSARY = [
{
"id": "term-absolute-reference",
"name": "Absolute Reference",
"aliases": [
"Absolute Reference"
],
"def": "A spreadsheet cell reference, written with dollar signs such as $H$1, that does not change when the formula is copied or filled.",
"example": "=D2*$H$1 keeps pointing at the GST rate cell.",
"link": true
},
{
"id": "term-abstraction",
"name": "Abstraction",
"aliases": [
"Abstraction"
],
"def": "The process by which data and programs are defined with a representation similar in form to its meaning while hiding away the implementation details. Abstraction tries to temporarily ignore details so that the programmer can focus on a few concepts at a time. Algorithms must ultimately be broken down into simple instructions for a digital system to execute.",
"example": "A train map shows stations and lines but hides the real curves of the track.",
"link": true
},
{
"id": "term-acceptance-testing",
"name": "Acceptance Testing",
"aliases": [
"Acceptance Testing"
],
"def": "Testing in which the client or users check the finished system against agreed criteria to decide whether to accept it.",
"example": "The canteen manager completes her daily tasks and signs off.",
"link": true
},
{
"id": "term-action-plan",
"name": "Action Plan",
"aliases": [
"Action Plan"
],
"def": "A short-range list of tasks with an owner, a due date and a status, usually drawn from a Gantt chart.",
"example": "A weekly table of who builds the Menu tables and by which day.",
"link": true
},
{
"id": "term-actuator",
"name": "Actuator",
"aliases": [
"Actuator"
],
"def": "A device that converts a control signal into a physical action, such as opening a valve or switching a relay.",
"example": "A vent actuator that opens when a greenhouse is too hot.",
"link": true
},
{
"id": "term-adaptive-maintenance",
"name": "Adaptive Maintenance",
"aliases": [
"Adaptive Maintenance"
],
"def": "Maintenance that changes a system to suit a change in its environment or requirements.",
"example": "Adding a new menu item or updating prices when the menu changes.",
"link": true
},
{
"id": "term-adjacency-matrix",
"name": "Adjacency Matrix",
"aliases": [
"Adjacency Matrix"
],
"def": "A grid that records which nodes in a graph are directly linked, using 1 (or a weight) for a link and 0 for none.",
"example": "Row A of a friendship matrix reads 0 1 1 1 0 0, so A is linked to B, C and D.",
"link": true
},
{
"id": "term-aggregation",
"name": "Aggregation",
"aliases": [
"Aggregation"
],
"def": "Combining many records into a summary such as a total, average or count for each group.",
"example": "Total takings for each month.",
"link": true
},
{
"id": "term-agile-approach",
"name": "Agile Approach",
"aliases": [
"Agile Approach",
"agile",
"agile development",
"agile methodology"
],
"def": "A development approach that builds the system in short cycles, each producing working output that the client reviews before the next cycle is planned.",
"example": "A club booking app delivered in two-week sprints, with the club secretary reviewing each one.",
"link": true
},
{
"id": "term-air-gap",
"name": "Air Gap",
"aliases": [
"Air Gap"
],
"def": "Keeping a system physically or logically disconnected from other networks so it cannot be reached across them.",
"example": "An offline backup server that is never connected to the office network.",
"link": true
},
{
"id": "term-algorithm",
"name": "Algorithm",
"aliases": [
"Algorithm"
],
"def": "A step-by-step procedure required to solve a problem. Algorithms may be presented in many ways, e.g. written instructions, flow charts or using a computer programming language.",
"example": "The steps a canteen app follows to total an order: add each price, apply the discount, then add GST.",
"link": true
},
{
"id": "term-alternative-data",
"name": "Alternative Data",
"aliases": [
"Alternative Data"
],
"def": "Data from non-traditional sources, such as likes, emoticons and memes, used as quick feedback about a product or message.",
"example": "A surge of angry-face reactions on a post about a new e-bike.",
"link": true
},
{
"id": "term-app",
"name": "App",
"aliases": [
"App"
],
"def": "A software program designed for a specific purpose to run on mobile devices or on a personal computer. An abbreviation of the word ‘application’.",
"example": "A school canteen ordering app on a phone.",
"link": false
},
{
"id": "term-artificial-intelligence",
"name": "Artificial Intelligence (AI)",
"aliases": [
"AI",
"Artificial Intelligence"
],
"def": "Intelligence demonstrated by machines. Sometimes called machine intelligence.",
"example": "A spam filter that learns to recognise junk email.",
"link": true
},
{
"id": "term-assets",
"name": "Assets",
"aliases": [
"Assets"
],
"def": "Assets are the digital elements that can be used or incorporated into a multimedia presentation or production. They include graphics, photographs, videos, audio, animations or other artistic data.",
"example": "A logo in SVG, a photo in JPEG and an interview in MP4 used on one website.",
"link": false
},
{
"id": "term-attenuation",
"name": "Attenuation",
"aliases": [
"Attenuation"
],
"def": "The weakening of a signal as it travels through a medium or across distance.",
"example": "An Ethernet cable run beyond about 100 m loses too much signal to work reliably.",
"link": true
},
{
"id": "term-augmented-reality",
"name": "Augmented Reality (AR)",
"aliases": [
"AR",
"Augmented Reality"
],
"def": "A technology that replicates, enhances or overlays extra information about the real-world environment, using computer-generated data such as global positioning systems (GPS), sound, videos and images. Common examples include a car windshield with a heads-up display (HUD) that projects three-dimensional navigation information and virtual lanes, or a swimming telecast using a line to indicate the position of the record holder in relation to the actual swimmers in the race.",
"example": "A phone app that shows how a sofa would look in your lounge room through the camera.",
"link": true
},
{
"id": "term-auto-profiling",
"name": "Auto-profiling",
"aliases": [
"Auto-profiling"
],
"def": "The automatic building of a picture of a person by inferring interests and characteristics from their behaviour without them entering it.",
"example": "A video app recommending content based on what you watched, not on what you said you liked.",
"link": true
},
{
"id": "term-automate",
"name": "Automate",
"aliases": [
"Automate"
],
"def": "The process of transforming and manipulating data that does not require user intervention. For example, through the use of formulae in a spreadsheet, new sets of data can be processed and the results recalculated automatically, or a webcam can be turned on as a result of movement sensor input.",
"example": "A spreadsheet total that recalculates by itself whenever a price is changed.",
"link": false
},
{
"id": "term-backup-rule",
"name": "Backup Rule (3-2-1)",
"aliases": [
"3-2-1",
"3-2-1 backup",
"3-2-1 backup rule",
"Backup Rule"
],
"def": "A backup guideline of keeping three copies of data on two types of media, with one copy offsite.",
"example": "Live data on a server, a copy on a storage device, and a copy on tape at another site.",
"link": true
},
{
"id": "term-backward-chaining",
"name": "Backward Chaining",
"aliases": [
"Backward Chaining"
],
"def": "A technique used by inference engines that determines reasoning from the knowledge base to understand how a decision was made. In backward chaining, the goal or output is used to track back to establish the steps taken.",
"example": "To prove repot_with_drainage, the engine checks root_rot_risk, then overwatered, then the observed facts.",
"link": true
},
{
"id": "term-bandwidth",
"name": "Bandwidth",
"aliases": [
"Bandwidth"
],
"def": "The maximum amount of data a connection can carry per second, usually measured in megabits per second.",
"example": "A 100 Mbps nbn plan can carry up to 100 megabits each second.",
"link": true
},
{
"id": "term-beta-testing",
"name": "Beta Testing",
"aliases": [
"Beta Testing"
],
"def": "Testing a near-final version of a system with a limited group of real users outside the development team to find remaining faults.",
"example": "Fifty students trial a new school app for a fortnight.",
"link": true
},
{
"id": "term-betweenness-centrality",
"name": "Betweenness Centrality",
"aliases": [
"Betweenness Centrality"
],
"def": "A measure of how often a node lies on the shortest paths between other pairs of nodes, showing which nodes act as bridges.",
"example": "A switch that joins two office floors carries most cross-floor traffic, so it has high betweenness.",
"link": true
},
{
"id": "term-big-data",
"name": "Big Data",
"aliases": [
"Big Data"
],
"def": "Extremely large datasets that may be analysed computationally to reveal patterns, trends and associations.",
"example": "A GPS point logged every few seconds for every bike in a scheme.",
"link": true
},
{
"id": "term-biometric",
"name": "Biometric",
"aliases": [
"Biometric"
],
"def": "A term that describes the source of data being human or biological.",
"example": "A fingerprint or face scan used to unlock a phone.",
"link": true
},
{
"id": "term-bit-depth",
"name": "Bit Depth",
"aliases": [
"Bit Depth"
],
"def": "The number of bits used to record each sample or pixel, which sets how many different values can be stored.",
"example": "16-bit audio allows 65,536 possible heights per sample; 24-bit colour allows about 16.7 million colours.",
"link": true
},
{
"id": "term-bitmap-graphic",
"name": "Bitmap Graphic",
"aliases": [
"Bitmap Graphic",
"bitmap",
"bitmap image",
"raster image"
],
"def": "An image made from a grid of pixels, each with its own colour, so it blurs or pixelates when enlarged.",
"example": "A photograph saved as a JPEG or a screenshot saved as a PNG.",
"link": true
},
{
"id": "term-blockchain",
"name": "Blockchain",
"aliases": [
"Blockchain"
],
"def": "A growing list of records, known as blocks, which are linked using cryptography. It can be used to record transactions between 2 parties efficiently and in a verifiable and permanent way.",
"example": "Each block stores the hash of the previous block, so editing one block breaks every later link.",
"link": true
},
{
"id": "term-botnet",
"name": "Botnet",
"aliases": [
"Botnet"
],
"def": "A network of infected devices (bots) controlled remotely by an attacker, often to run a DDoS attack or send spam.",
"example": "Thousands of infected home routers flood a website with requests at once.",
"link": true
},
{
"id": "term-boundary-data",
"name": "Boundary Test Data",
"aliases": [
"Boundary Test Data",
"boundary data",
"boundary test"
],
"def": "Test values that lie on the limit of an allowed range and immediately either side of it.",
"example": "For a booking length of 30 to 120 minutes, the boundary values are 29, 30, 120 and 121.",
"link": true
},
{
"id": "term-business-email-compromise",
"name": "Business Email Compromise",
"aliases": [
"BEC",
"Business Email Compromise"
],
"def": "A scam that takes over or imitates a business email account to trick staff into sending payments or data to a criminal.",
"example": "An email that appears to be from a supplier asks for a payment to a new bank account.",
"link": true
},
{
"id": "term-calculate",
"name": "Calculate",
"aliases": [
"Calculate"
],
"def": "Ascertain/determine from given facts, figures or information.",
"example": "Calculate the total cost of 12 items at $4.50 each, including 10% GST.",
"link": false
},
{
"id": "term-captcha",
"name": "CAPTCHA",
"aliases": [
"CAPTCHA"
],
"def": "Completely Automatic Public Turing Test to Tell Computers and Humans Apart.",
"example": "A sign-up form that asks you to pick every image containing a bus before it lets you continue.",
"link": true
},
{
"id": "term-care-principles",
"name": "CARE Principles",
"aliases": [
"CARE Principles"
],
"def": "Principles for Indigenous data governance from the Global Indigenous Data Alliance: Collective benefit, Authority to control, Responsibility and Ethics.",
"example": "A research team agrees with an Aboriginal community-controlled organisation how its data will be stored and shared.",
"link": true
},
{
"id": "term-certainty-factor",
"name": "Certainty Factor (CF)",
"aliases": [
"CF",
"Certainty Factor"
],
"def": "A number, here from 0 to 1, that shows how strongly a piece of evidence or a rule is believed.",
"example": "A rule with CF 0.8 and evidence with CF 0.7 gives a conclusion with CF 0.56.",
"link": true
},
{
"id": "term-change-request",
"name": "Change Request",
"aliases": [
"Change Request"
],
"def": "A formal request to alter something already agreed, assessed for its effect on cost, time and scope before it is accepted.",
"example": "The committee asks for a waiting list and the team costs it before agreeing to add it.",
"link": true
},
{
"id": "term-cherry-picking",
"name": "Cherry-picking",
"aliases": [
"Cherry-picking"
],
"def": "Choosing only the data, date range or results that support a preferred conclusion.",
"example": "Showing July to December sales growth and hiding the January to June decline.",
"link": true
},
{
"id": "term-cia-triad",
"name": "CIA Triad",
"aliases": [
"CIA Triad"
],
"def": "The three attributes of information security: confidentiality, integrity and availability.",
"example": "Ransomware that locks files breaches availability; a leaked database breaches confidentiality.",
"link": true
},
{
"id": "term-clarify",
"name": "Clarify",
"aliases": [
"Clarify"
],
"def": "Make clear or plain.",
"example": "Clarify the client’s need by asking what \"faster booking\" means: fewer clicks or a quicker page load.",
"link": false
},
{
"id": "term-classify",
"name": "Classify",
"aliases": [
"Classify"
],
"def": "Arrange or include in classes/categories.",
"example": "Classify survey answers as quantitative (a rating out of 5) or qualitative (a written comment).",
"link": false
},
{
"id": "term-cloud-computing",
"name": "Cloud Computing",
"aliases": [
"Cloud Computing"
],
"def": "Distributing computing over a network where storage of files, processing of data and/or access to software occurs automatically on interconnected server computers to which the user’s device is connected. The term refers to accessing files, software and services over the internet.",
"example": "A small business keeps its files in a cloud drive and pays each month for exactly the storage it uses.",
"link": true
},
{
"id": "term-collaborate",
"name": "Collaborate",
"aliases": [
"Collaborate"
],
"def": "Working with others towards a shared goal, through a variety of modes of communication. This may be achieved using a range of technologies, tools and processes.",
"example": "A project team edits one shared design document and agrees decisions in a weekly meeting.",
"link": false
},
{
"id": "term-computational-thinking",
"name": "Computational Thinking",
"aliases": [
"Computational Thinking"
],
"def": "A process in which a problem is analysed and solved so that a human, machine or computer can effectively implement the solution. It involves using strategies to organise data logically, break down problems into parts, interpret patterns and design, and implement algorithms to solve problems.",
"example": "Breaking \"run the school canteen online\" into ordering, paying and preparing, then solving each part separately.",
"link": true
},
{
"id": "term-conditional-formatting",
"name": "Conditional Formatting",
"aliases": [
"Conditional Formatting"
],
"def": "A spreadsheet feature that changes how a cell looks automatically when its value meets a rule.",
"example": "Shading a stock cell red when it falls below 10.",
"link": true
},
{
"id": "term-connectedness",
"name": "Connectedness",
"aliases": [
"Connectedness"
],
"def": "The property of a graph in which there is a path between every pair of nodes; a graph that is not connected splits into separate components.",
"example": "Cutting the only cable to a building leaves the network disconnected.",
"link": true
},
{
"id": "term-consensus-mechanism",
"name": "Consensus Mechanism",
"aliases": [
"Consensus Mechanism"
],
"def": "The rule a distributed network uses to agree on which new block or record is valid.",
"example": "Proof of work and proof of stake are two consensus mechanisms.",
"link": true
},
{
"id": "term-constraint",
"name": "Constraint",
"aliases": [
"Constraint"
],
"def": "A limit on a project, such as time, money, skills or equipment, that the team must work within.",
"example": "A six-week deadline and no budget for software.",
"link": true
},
{
"id": "term-contingency",
"name": "Contingency",
"aliases": [
"Contingency"
],
"def": "An amount of money or time set aside in a plan to cover problems that could not be foreseen.",
"example": "A budget of $690 adds a 10% contingency of $69.",
"link": true
},
{
"id": "term-cookie",
"name": "Cookie",
"aliases": [
"Cookie"
],
"def": "A small piece of data a website stores in the browser to keep a session, remember preferences or track activity.",
"example": "A shopping cart that remembers items after you close the tab.",
"link": true
},
{
"id": "term-copyright",
"name": "Copyright",
"aliases": [
"Copyright"
],
"def": "The legal right of a creator to control how their original work, such as text, images, music, video and software, is copied, shared and adapted. In Australia it arises automatically under the Copyright Act 1968.",
"example": "Reusing a photo from a website only if its licence allows, and acknowledging the creator.",
"link": true
},
{
"id": "term-corrective-maintenance",
"name": "Corrective Maintenance",
"aliases": [
"Corrective Maintenance"
],
"def": "Maintenance that finds and fixes faults reported after a system has been put into use.",
"example": "Fixing an import that fails when an item name has a trailing space.",
"link": true
},
{
"id": "term-creative-commons",
"name": "Creative Commons",
"aliases": [
"Creative Commons"
],
"def": "Is a non-profit organisation that enables the sharing of creative content without the need to seek legal approval.",
"example": "A photo licensed CC BY 4.0 that you can reuse if you credit the creator.",
"link": true
},
{
"id": "term-credential-stuffing",
"name": "Credential Stuffing",
"aliases": [
"Credential Stuffing"
],
"def": "An attack that automatically tries username and password pairs leaked from one breach on other sites, relying on password reuse.",
"example": "Stolen email and password pairs are tested against a streaming service login.",
"link": true
},
{
"id": "term-critical-path",
"name": "Critical Path",
"aliases": [
"Critical Path"
],
"def": "The longest chain of dependent tasks in a project plan, which decides the earliest finish date; a delay to any task on it delays the whole project.",
"example": "If the database build slips a day, the dependent screens, integration and testing all move back a day.",
"link": true
},
{
"id": "term-critically-analyse-evaluate",
"name": "Critically Analyse/Evaluate",
"aliases": [
"Critically Analyse/Evaluate"
],
"def": "Add a degree or level of accuracy, depth, knowledge and understanding, logic, questioning, reflection and quality to (analyse/evaluate).",
"example": "Weigh the strengths and weaknesses of a solution against its success criteria, question the evidence and reach a justified conclusion.",
"link": false
},
{
"id": "term-crowdsourcing",
"name": "Crowdsourcing",
"aliases": [
"Crowdsourcing"
],
"def": "Using a large group of people, usually online, to contribute information, ideas or work.",
"example": "Residents reporting flood levels through a community social media page.",
"link": true
},
{
"id": "term-cyber-safety",
"name": "Cyber Safety",
"aliases": [
"Cyber Safety"
],
"def": "A term that refers to behaviour and the precautions that may be exercised when providing personal information in an online or digital environment.",
"example": "Keeping your address and birth date private on a public profile.",
"link": true
},
{
"id": "term-cybersecurity",
"name": "Cybersecurity",
"aliases": [
"Cybersecurity"
],
"def": "The protection of information technology elements, including hardware and software, data or network services.",
"example": "A business patches its software, backs up its data and uses multi-factor authentication.",
"link": false
},
{
"id": "term-dark-pattern",
"name": "Dark Pattern",
"aliases": [
"Dark Pattern"
],
"def": "A deceptive design technique that steers users into choices that are not in their interest.",
"example": "A cancel link hidden behind five clicks while sign-up takes one.",
"link": true
},
{
"id": "term-dashboard",
"name": "Dashboard",
"aliases": [
"Dashboard"
],
"def": "A single screen that brings together the key figures, charts and controls someone needs to monitor a system or make a decision.",
"example": "Canteen Insights shows revenue, items sold, top seller and waste, with a line chart, a bar chart and a reorder list on one page.",
"link": true
},
{
"id": "term-data",
"name": "Data",
"aliases": [
"Data"
],
"def": "A discrete representation of information using number codes. Data may include characters (e.g. alphabetic letters, numbers and symbols), images, sounds and/or instructions that, when represented by number codes, can be manipulated, stored and communicated by digital systems. For example, characters may be represented using ASCII code or images may be represented by a bitmap of numbers representing each ‘dot’ or pixel.",
"example": "The letter A stored as the number 65 in ASCII, or a photo stored as a grid of pixel colour numbers.",
"link": false
},
{
"id": "term-data-bias",
"name": "Data Bias",
"aliases": [
"Data Bias"
],
"def": "A systematic tilt in how data is collected, analysed or used, so that results consistently lean in one direction.",
"example": "Surveying only app users, so riders without smartphones are missing from the results.",
"link": true
},
{
"id": "term-data-compression",
"name": "Data Compression",
"aliases": [
"Data Compression"
],
"def": "A reduction in the number of bits needed to represent data.",
"example": "Saving a photo as a JPEG so it downloads faster.",
"link": true
},
{
"id": "term-data-cube",
"name": "Data Cube",
"aliases": [
"Data Cube"
],
"def": "A multidimensional arrangement of data in which each cell holds a measure at the intersection of several dimensions.",
"example": "A cube of sales with Product, Quarter and Region as its three dimensions.",
"link": true
},
{
"id": "term-data-dictionary",
"name": "Data Dictionary",
"aliases": [
"Data Dictionary"
],
"def": "A comprehensive description of each field in a database, commonly listing the field name, data type, data format, field size, description and an example.",
"example": "UserID: Text, XXXNNNN, size 7, example XYZ1539.",
"link": true
},
{
"id": "term-data-flow-diagram",
"name": "Data Flow Diagram (DFD)",
"aliases": [
"DFD",
"Data Flow Diagram"
],
"def": "A diagram that shows how data moves between external entities, processes and data stores, using circles for processes, open-ended rectangles for data stores, closed rectangles for external entities and labelled curved arrows for data flows.",
"example": "A voting system DFD showing Voters sending their details and vote to the Voting process.",
"link": true
},
{
"id": "term-data-integrity",
"name": "Data Integrity",
"aliases": [
"Data Integrity"
],
"def": "The accuracy, completeness, consistency and trustworthiness of data across its whole life.",
"example": "Validation checks and access controls that stop a price of 5500 replacing 55.00.",
"link": true
},
{
"id": "term-data-journalism",
"name": "Data Journalism",
"aliases": [
"Data Journalism"
],
"def": "Finding, analysing and presenting data to tell a news story, often using interactive charts or maps.",
"example": "An interactive map letting readers look up rainfall in their own town.",
"link": true
},
{
"id": "term-data-literacy",
"name": "Data Literacy",
"aliases": [
"Data Literacy"
],
"def": "The ability to read, understand, question and communicate with data.",
"example": "Checking who collected a chart's data, how big the sample was and whether the axis starts at zero.",
"link": true
},
{
"id": "term-data-minimisation",
"name": "Data Minimisation",
"aliases": [
"Data Minimisation"
],
"def": "The principle of collecting and keeping only the personal information that is needed for a stated purpose.",
"example": "A quiz app that asks only for an email address, not a birth date.",
"link": true
},
{
"id": "term-data-mining",
"name": "Data Mining",
"aliases": [
"Data Mining"
],
"def": "Discovering patterns, relationships and unusual values in large datasets using statistics and machine learning.",
"example": "Finding groups of riders with similar travel habits so that passes can be designed for each.",
"link": true
},
{
"id": "term-data-retention",
"name": "Data Retention",
"aliases": [
"Data Retention"
],
"def": "The rule for how long data are kept before they are deleted or summarised.",
"example": "Keeping item-level sales rows for 12 months, then reducing them to weekly totals.",
"link": true
},
{
"id": "term-data-sampling",
"name": "Data Sampling",
"aliases": [
"Data Sampling"
],
"def": "The practice of analysing a subset of a larger dataset in order to determine meaningful information such as patterns and trends.",
"example": "Surveying 200 students to learn about the habits of a school of 1,200.",
"link": true
},
{
"id": "term-data-sovereignty",
"name": "Data Sovereignty",
"aliases": [
"Data Sovereignty"
],
"def": "This is a global movement that refers to the right of Indigenous Peoples to determine the creation, collection, ownership and application of data that is for and about Indigenous Peoples. The term also refers to transnational data flow and a range of issues arising from the flow of data between nations.",
"example": "An Aboriginal community-controlled organisation decides how data about its community is collected, stored and used; a business chooses an Australian cloud region so customer records stay under Australian law.",
"link": true
},
{
"id": "term-data-store",
"name": "Data Store",
"aliases": [
"Data Store"
],
"def": "A place where data is kept between processes, either an electronic file or non-computer storage; drawn as a rectangle open on one side in a DFD.",
"example": "An Electoral roll in a voting system.",
"link": true
},
{
"id": "term-data-swamp",
"name": "Data Swamp",
"aliases": [
"Data Swamp"
],
"def": "A data lake that has become unusable because nothing records what the data is, where it came from, its quality or who owns it.",
"example": "A store of thousands of unlabelled, duplicate files that analysts cannot trust.",
"link": true
},
{
"id": "term-data-types",
"name": "Data Types",
"aliases": [
"Data Types"
],
"def": "Data types used in computing are expressed as either: string/text, character, integer, floating point or real, date and time or Boolean.",
"example": "A price is a floating point number, a quantity is an integer and a booking date is date and time.",
"link": true
},
{
"id": "term-data-warehouse",
"name": "Data Warehouse",
"aliases": [
"Data Warehouse"
],
"def": "A large central store of consistent, historical data from many operational systems, organised for analysis and reporting.",
"example": "A retailer loads nightly sales from 90 stores into one warehouse and compares years.",
"link": true
},
{
"id": "term-database",
"name": "Database",
"aliases": [
"Database"
],
"def": "A collection of data organised by records and fields that can be easily stored, accessed, managed and updated.",
"example": "A canteen keeps its items, prices and orders in tables of records and fields.",
"link": false
},
{
"id": "term-dataset",
"name": "Dataset",
"aliases": [
"Dataset"
],
"def": "A collection of data combined for a specific purpose.",
"example": "A year of bike-share trips gathered to study which stations are busiest.",
"link": true
},
{
"id": "term-days-of-stock",
"name": "Days of Stock",
"aliases": [
"Days of Stock"
],
"def": "The number of trading days the stock on hand will last at the current average rate of sales, found by dividing stock on hand by average daily sales.",
"example": "58 bottles on hand and 36 sold a day gives about 1.6 days of stock.",
"link": true
},
{
"id": "term-decision-support-system",
"name": "Decision Support System (DSS)",
"aliases": [
"DSS",
"Decision Support System"
],
"def": "An information system that combines data, a model and an interface to help people make decisions, without making them alone.",
"example": "A supermarket tool that forecasts demand and suggests next week's order for a manager to adjust.",
"link": true
},
{
"id": "term-decision-tree",
"name": "Decision Tree",
"aliases": [
"Decision Tree"
],
"def": "A diagram that represents all possible combinations of decisions and their resulting actions, where each path leads to another decision or a final action.",
"example": "A tree that decides whether to buy a car from its mileage, type and colour.",
"link": true
},
{
"id": "term-deepfake",
"name": "Deepfake",
"aliases": [
"Deepfake"
],
"def": "Synthetic audio, image or video created with artificial intelligence to imitate a real person.",
"example": "A cloned voice of a manager asking for an urgent payment.",
"link": true
},
{
"id": "term-degree-centrality",
"name": "Degree Centrality",
"aliases": [
"Degree Centrality"
],
"def": "A measure of a node's importance based on the number of edges connected to it.",
"example": "A user with 3 friends in a six-person network has degree 3 and normalised degree centrality 3 ÷ 5 = 0.6.",
"link": true
},
{
"id": "term-deliverable",
"name": "Deliverable",
"aliases": [
"Deliverable"
],
"def": "A specific item that a project must produce and hand over, such as a working system, a user guide or a test report.",
"example": "The user guide handed to the canteen manager.",
"link": true
},
{
"id": "term-design-thinking",
"name": "Design Thinking",
"aliases": [
"Design Thinking"
],
"def": "A process where a need or opportunity is identified and a design solution is developed. The consideration of economic, environmental and social impacts that result from designed solutions are core to design thinking. Design thinking methods can be used when trying to understand a problem, generate ideas and refine a design based on evaluation and testing.",
"example": "Interviewing students about lunch queues, then testing a paper prototype of an ordering site.",
"link": true
},
{
"id": "term-dice",
"name": "Dice",
"aliases": [
"Dice"
],
"def": "An OLAP operation that selects a sub-cube by choosing values on two or more dimensions.",
"example": "Dicing for Coffee and Cake in Q3 and Q4 across both regions.",
"link": false
},
{
"id": "term-digital-citizenship",
"name": "Digital Citizenship",
"aliases": [
"Digital Citizenship"
],
"def": "An acceptance and upholding of the norms of appropriate, responsible behaviour with regard to the use of digital technologies.",
"example": "Checking a claim before sharing it and asking permission before posting a photo of a friend.",
"link": true
},
{
"id": "term-digital-footprint",
"name": "Digital Footprint",
"aliases": [
"Digital Footprint"
],
"def": "Traces of data left behind by a person using a digital system. A person’s digital footprint includes all information actively provided by that person, such as interactions on social networks, online purchases, emails and instant messages. It also includes passive information, such as logs of software installed and used on a computer, metadata associated with files, a user’s internet protocol (IP) address, a device being used to access a webpage, and a user’s browsing history stored as cookies or by internet service providers.",
"example": "Posts you share (active) and your IP address in server logs (passive).",
"link": true
},
{
"id": "term-digital-technologies",
"name": "Digital Technologies",
"aliases": [
"Digital Technologies"
],
"def": "Refers to electronic tools, systems, devices and resources that generate, process or store data, and may include applications, games, microcontrollers, mobile devices, multimedia, networks, robotics.",
"example": "A tablet, a robot vacuum, a school network and a game console.",
"link": false
},
{
"id": "term-digital-twin",
"name": "Digital Twin",
"aliases": [
"Digital Twin"
],
"def": "A virtual copy of a physical machine, building or process that is updated with live sensor data and used to test changes and predict faults.",
"example": "A model of a pump that shows when its vibration pattern suggests a failure.",
"link": true
},
{
"id": "term-dimension",
"name": "Dimension",
"aliases": [
"Dimension"
],
"def": "A category by which data is viewed and grouped in analysis, often with a hierarchy of levels.",
"example": "Time is a dimension with the levels year, quarter, month and day.",
"link": false
},
{
"id": "term-disruptive-technology",
"name": "Disruptive Technology",
"aliases": [
"Disruptive Technology"
],
"def": "A technology that changes how people or organisations do something so much that established products, services or business models are displaced.",
"example": "Streaming services displaced most DVD rental shops.",
"link": true
},
{
"id": "term-distributed-ledger",
"name": "Distributed Ledger",
"aliases": [
"Distributed Ledger"
],
"def": "A record of transactions held as identical copies on many computers (nodes), with no single master copy.",
"example": "Every node in a public blockchain stores the full chain of blocks.",
"link": true
},
{
"id": "term-drill-down",
"name": "Drill-down",
"aliases": [
"Drill-down"
],
"def": "Moving down a hierarchy to see more detailed data.",
"example": "Going from quarterly sales to the three months in that quarter.",
"link": true
},
{
"id": "term-edge",
"name": "Edge",
"aliases": [
"Edge"
],
"def": "A line in a graph that joins two nodes and may carry a label or a weight. Also called a link.",
"example": "A friendship between two users, or a cable of 25 m between two buildings.",
"link": false
},
{
"id": "term-edge-computing",
"name": "Edge Computing",
"aliases": [
"Edge Computing"
],
"def": "A computing framework that allows for the distribution of processing capabilities and hardware so that applications can be closer to their data source.",
"example": "A gateway on a farm that decides when to switch a pump on without waiting for the cloud.",
"link": true
},
{
"id": "term-encryption",
"name": "Encryption",
"aliases": [
"Encryption"
],
"def": "A process in cryptography of encoding (converting) data, using mathematical formulas, into a form that only an intended recipient can decode, often including a personal digital signature.",
"example": "A messaging app scrambles each message so that only the recipient’s device can read it.",
"link": true
},
{
"id": "term-end-user-development",
"name": "End-User Development",
"aliases": [
"End-User Development"
],
"def": "A development approach in which the people who will use the system build or adapt it themselves, usually with accessible tools such as spreadsheets or no-code software.",
"example": "A club secretary builds a membership tracker in a spreadsheet.",
"link": true
},
{
"id": "term-enterprise",
"name": "Enterprise",
"aliases": [
"Enterprise"
],
"def": "An activity that produces goods and/or services. Enterprises are run for the benefit of an individual or a group of individuals. They can range in scale from a transnational corporation to home-based economic activities.",
"example": "A local bakery that takes online orders and tracks its stock in a spreadsheet.",
"link": false
},
{
"id": "term-enterprise-computing",
"name": "Enterprise Computing",
"aliases": [
"Enterprise Computing"
],
"def": "Refers to business-oriented information technology that is critical to a company’s operations. Enterprise computing encompasses types of information technology tools that businesses use for resource management, efficient production operations, relationship management and back office support.",
"example": "A retailer’s stock control, sales reporting and customer database working together.",
"link": false
},
{
"id": "term-enterprise-system",
"name": "Enterprise System",
"aliases": [
"Enterprise System"
],
"def": "The combination of digital systems, people and processes that collect, manage and analyse data.",
"example": "A club’s booking system: staff and members (people), a booking process, and a database that stores and reports on bookings.",
"link": true
},
{
"id": "term-erroneous-data",
"name": "Erroneous Test Data",
"aliases": [
"Erroneous Test Data",
"erroneous data",
"erroneous test"
],
"def": "Test data that the system should reject, such as data of the wrong type, an impossible value or a missing entry.",
"example": "Entering \"abc\" or leaving a blank for a booking length.",
"link": true
},
{
"id": "term-essential-eight",
"name": "Essential Eight",
"aliases": [
"Essential Eight"
],
"def": "A set of eight mitigation strategies published by the Australian Signals Directorate, with maturity levels, to help organisations defend against cyber threats.",
"example": "Multi-factor authentication and regular backups are two of the eight.",
"link": true
},
{
"id": "term-etl",
"name": "ETL (Extract, Transform, Load)",
"aliases": [
"ETL"
],
"def": "The process of copying data from source systems, converting it to consistent formats and definitions, and loading it into a data warehouse.",
"example": "Matching old and new product codes before loading sales history.",
"link": true
},
{
"id": "term-evaluate",
"name": "Evaluate",
"aliases": [
"Evaluate"
],
"def": "Make a judgement based on criteria; determine the value of.",
"example": "Judge whether a new booking system met its success criteria, using test results and user feedback.",
"link": false
},
{
"id": "term-evil-twin",
"name": "Evil Twin",
"aliases": [
"Evil Twin"
],
"def": "A rogue Wi-Fi access point that copies a legitimate network's name so nearby devices connect to it and their traffic can be intercepted.",
"example": "An attacker broadcasts 'Cafe_Free_WiFi' next to a real cafe network.",
"link": true
},
{
"id": "term-expert-system",
"name": "Expert System",
"aliases": [
"Expert System"
],
"def": "A program that captures the knowledge of human experts as facts and IF–THEN rules and uses an inference engine to reach conclusions about a narrow topic.",
"example": "A help-desk system that diagnoses a printer fault from the lights a user reports.",
"link": true
},
{
"id": "term-explanation-facility",
"name": "Explanation Facility",
"aliases": [
"Explanation Facility"
],
"def": "A feature of an expert system that shows why a question was asked or how a conclusion was reached, usually by displaying the rules used.",
"example": "A tree showing that reduce_watering came from rule R5, which used overwatered, which came from rule R1.",
"link": true
},
{
"id": "term-external-entity",
"name": "External Entity",
"aliases": [
"External Entity"
],
"def": "A person, organisation or element outside a system that provides data to it or receives data from it.",
"example": "Students who place orders in a canteen ordering system.",
"link": true
},
{
"id": "term-extrapolation",
"name": "Extrapolation",
"aliases": [
"Extrapolation"
],
"def": "Extending a pattern beyond the range of the data used to find it, which makes predictions less reliable.",
"example": "Using a trend line built on 21 to 35°C data to predict boardings at 42°C.",
"link": true
},
{
"id": "term-feasibility-study",
"name": "Feasibility Study",
"aliases": [
"Feasibility Study",
"feasibility",
"feasibility check"
],
"def": "An assessment, made before a project is committed to, of whether it can succeed: technically, economically, operationally, on schedule and legally.",
"example": "A team checks that the planned cost is within budget and that volunteers can be trained before starting the build.",
"link": true
},
{
"id": "term-firewall",
"name": "Firewall",
"aliases": [
"Firewall"
],
"def": "Hardware or software that filters network traffic against a set of rules, allowing or blocking it.",
"example": "A firewall that denies all traffic from guest Wi-Fi to the staff network.",
"link": true
},
{
"id": "term-firmware",
"name": "Firmware",
"aliases": [
"Firmware"
],
"def": "Is the software that is installed on a small chip in almost all hardware devices that makes the hardware function as the manufacturer intended it to.",
"example": "The software on a home router that manufacturers update to fix security faults.",
"link": true
},
{
"id": "term-flat-file-database",
"name": "Flat-File Database",
"aliases": [
"Flat-File Database"
],
"def": "A database that stores all its data in a single table of records and fields.",
"example": "A single table of trips that repeats each rider's name on every row.",
"link": true
},
{
"id": "term-foreign-key",
"name": "Foreign Key",
"aliases": [
"Foreign Key"
],
"def": "A field in one table that holds the primary key value of a record in another table, creating a link between the tables.",
"example": "Publisher_ID in the Games table.",
"link": true
},
{
"id": "term-forward-chaining",
"name": "Forward Chaining",
"aliases": [
"Forward Chaining"
],
"def": "A technique used by inference engines that applies reasoning to the knowledge base to get the information to make a decision. In forward chaining, the inference engine evaluates existing data to develop new data to make a decision.",
"example": "Starting from leaves_yellow and soil_wet, an engine adds overwatered and then reduce_watering.",
"link": true
},
{
"id": "term-freelance-work",
"name": "Freelance Work",
"aliases": [
"Freelance Work"
],
"def": "Work done by a self-employed person who takes on tasks or projects for one or more clients rather than being an employee.",
"example": "A club hires a freelance designer to create the screens for its booking system.",
"link": true
},
{
"id": "term-function",
"name": "Function",
"aliases": [
"Function"
],
"def": "A term used in programming to describe a self-contained sequence of instructions that performs a specific task or tasks and is designed to be able to be reused throughout the program. Functions often accept some kind of input, perform some process on that input, and return a result that can be used by other parts of a program. Most programming languages allow for user-defined functions, but will also provide pre-defined functions.",
"example": "A programmer writes calculateGST(price) once and calls it wherever a price needs GST.",
"link": false
},
{
"id": "term-functional-requirement",
"name": "Functional Requirement",
"aliases": [
"Functional Requirement"
],
"def": "A statement of something a system must do.",
"example": "The system must show the top seller for any chosen weeks.",
"link": true
},
{
"id": "term-fuzzy-logic",
"name": "Fuzzy Logic",
"aliases": [
"Fuzzy Logic"
],
"def": "Reasoning with degrees of truth between 0 and 1 instead of only true or false.",
"example": "A temperature of 24 degrees is Warm to degree 0.6 and Hot to degree 0.4.",
"link": true
},
{
"id": "term-gamification",
"name": "Gamification",
"aliases": [
"Gamification"
],
"def": "The adjustment of a task using digital technologies into a computer game in an attempt to make it more appealing.",
"example": "A learning app that awards points, badges and streaks for completing lessons.",
"link": true
},
{
"id": "term-gantt-chart",
"name": "Gantt Chart",
"aliases": [
"Gantt Chart"
],
"def": "A chart that displays each task of a project on an estimated, dated timeline, showing dependencies, milestones and, where used, resources and percentage complete.",
"example": "A requirements-gathering chart from 30 August to 16 September with a milestone diamond.",
"link": true
},
{
"id": "term-generative-ai",
"name": "Generative AI",
"aliases": [
"Generative AI"
],
"def": "Artificial intelligence that produces new content, such as text, images, audio or code, from patterns learned in very large datasets.",
"example": "A chatbot that drafts a summary of a meeting from a transcript.",
"link": true
},
{
"id": "term-graph-network-theory",
"name": "Graph and Network Theory",
"aliases": [
"Graph and Network Theory",
"graph theory",
"network theory"
],
"def": "The representation of individuals or categories as nodes and their relationships as links, applied to the design of social networks.",
"example": "A graph of VB's social network with links labelled Friend, Listen and Watch.",
"link": true
},
{
"id": "term-haptic",
"name": "Haptic",
"aliases": [
"Haptic"
],
"def": "Refers to the sense of touch. Often used to describe a method of output from a device that can be measured by feel or touch.",
"example": "A phone that vibrates when you tap a button.",
"link": true
},
{
"id": "term-hardware",
"name": "Hardware",
"aliases": [
"Hardware"
],
"def": "The collection of physical components that constitute a computer system, all of which are tangible objects. Hardware includes both internal and external components of the system, as well as any peripheral devices that can be connected.",
"example": "A keyboard, a router and a hard drive.",
"link": false
},
{
"id": "term-hash-function",
"name": "Hash Function",
"aliases": [
"Hash Function",
"hashing"
],
"def": "A function that turns any input into a fixed-length output (a hash) that changes completely if the input changes and cannot practically be reversed.",
"example": "SHA-256 turns a block of transactions into a 64-character fingerprint.",
"link": true
},
{
"id": "term-heuristic",
"name": "Heuristic",
"aliases": [
"Heuristic"
],
"def": "An experience-based rule of thumb that finds a good-enough answer quickly without guaranteeing the best one.",
"example": "A mechanic's rule to check the battery first.",
"link": true
},
{
"id": "term-hybrid-cloud",
"name": "Hybrid Cloud",
"aliases": [
"Hybrid Cloud"
],
"def": "A combination of private (or on-premises) infrastructure and public cloud, connected so data and applications can move between them.",
"example": "A clinic keeps active records on its own server and copies encrypted backups to a public cloud region.",
"link": true
},
{
"id": "term-hypothetical-reasoning",
"name": "Hypothetical Reasoning",
"aliases": [
"Hypothetical Reasoning"
],
"def": "A technique that follows the consequences of an assumption in a separate context, then adopts or discards it.",
"example": "A roster system assuming a nurse works Thursday night and rejecting the option after a rest-period clash.",
"link": true
},
{
"id": "term-implementation-plan",
"name": "Implementation Plan",
"aliases": [
"Implementation Plan"
],
"def": "A plan for how a new system goes live, including the changeover method, steps and dates, training, risks and a fallback.",
"example": "A pilot in one depot, then rollout to four others, with the old system kept for a fortnight.",
"link": true
},
{
"id": "term-icip",
"name": "Indigenous Cultural and Intellectual Property (ICIP)",
"aliases": [
"ICIP",
"Indigenous Cultural and Intellectual Property"
],
"def": "The rights of Aboriginal and Torres Strait Islander Peoples in their cultural heritage, including knowledge, art, stories, languages and designs.",
"example": "Asking the relevant community for permission before using traditional artwork on a website.",
"link": true
},
{
"id": "term-inference-engine",
"name": "Inference Engine",
"aliases": [
"Inference Engine"
],
"def": "The part of an expert system that applies the rules in the knowledge base to the known facts to reach conclusions.",
"example": "An engine that fires a rule to add overwatered to working memory, then fires the next rule.",
"link": true
},
{
"id": "term-informatics",
"name": "Informatics",
"aliases": [
"Informatics"
],
"def": "The science of processing data for storage and retrieval.",
"example": "Organising a bike-share's trip records into tables, summarising them and presenting a dashboard to the operations manager.",
"link": true
},
{
"id": "term-information",
"name": "Information",
"aliases": [
"Information"
],
"def": "The presentation of data in a manner that is readily understood.",
"example": "A chart showing that Friday is the busiest day, built from thousands of raw sales records.",
"link": false
},
{
"id": "term-information-system",
"name": "Information System",
"aliases": [
"Information System"
],
"def": "The combination of digital systems, people and processes that collect, manage and analyse data.",
"example": "A school’s attendance system: staff and students, roll-marking procedures, and software that records and reports absences.",
"link": true
},
{
"id": "term-iaas",
"name": "Infrastructure as a Service (IaaS)",
"aliases": [
"IaaS",
"Infrastructure as a Service"
],
"def": "A cloud service in which the provider supplies virtual servers, storage and networking and the customer manages the operating system and software.",
"example": "Renting a virtual server in a Sydney cloud region to run a legacy program.",
"link": true
},
{
"id": "term-input-validation",
"name": "Input Validation",
"aliases": [
"Input Validation"
],
"def": "Checks made on data as it is entered so that impossible or badly formed values are refused, using checks such as presence, type, range and format.",
"example": "Refusing a sold quantity of 'abc', -5 or 47 when only 46 items were prepared.",
"link": true
},
{
"id": "term-intelligent-agent",
"name": "Intelligent Agent",
"aliases": [
"Intelligent Agent"
],
"def": "A program that senses its environment, decides and acts to achieve a goal, from simple rule-following agents to complex learning agents.",
"example": "A web crawler that follows links (simple) and a ranking system that learns from clicks (complex).",
"link": true
},
{
"id": "term-intelligent-system",
"name": "Intelligent System",
"aliases": [
"Intelligent System"
],
"def": "A collective term for enterprise-based information systems that have the capacity to gather and/or analyse data and communicate with other systems, learn and produce targeted output to respond to the world around them.",
"example": "A greenhouse controller that reads sensors, learns from past results and adjusts the vents and watering.",
"link": true
},
{
"id": "term-interactive-media-systems",
"name": "Interactive Media Systems",
"aliases": [
"Interactive Media Systems"
],
"def": "Where there is facility for a user to interact with multimedia, the term ‘interactive media’ may be used. The use of digital technologies to present combinations of text, graphics, video, animation and/or sound in an integrated way. For example, interactive games, media-rich websites and electronic books (e-books).",
"example": "An interactive game, a media-rich website or an e-book.",
"link": true
},
{
"id": "term-internet-of-me",
"name": "Internet of Me (IoMe)",
"aliases": [
"Internet of Me",
"IoMe"
],
"def": "The internet of me (IoMe) loosely refers to technology which connects our minds and bodies with the online world. It transforms our biological and cognitive life into streams of data which can be monitored, shared and shaped.",
"example": "A smartwatch that records heart rate and sleep and shares them with a health app.",
"link": true
},
{
"id": "term-internet-of-things",
"name": "Internet of Things (IoT)",
"aliases": [
"Internet of Things",
"IoT"
],
"def": "Internet of Things (IoT) encompasses smart devices and smart objects that send and receive information using the internet and communication infrastructure.",
"example": "A soil moisture sensor that reports readings to a farm's irrigation system.",
"link": true
},
{
"id": "term-interoperability",
"name": "Interoperability",
"aliases": [
"Interoperability"
],
"def": "The ability of devices and systems from different makers to work together and exchange data.",
"example": "A light bulb from one brand and a hub from another both supporting the Matter standard.",
"link": true
},
{
"id": "term-iterative-development",
"name": "Iterative Development",
"aliases": [
"Iterative Development"
],
"def": "Repeating a cycle of design, build, test and review so that each pass improves the system using feedback.",
"example": "A paper prototype of a booking screen is tested, redrawn and tested again before any code is written.",
"link": true
},
{
"id": "term-kpi",
"name": "Key Performance Indicator (KPI)",
"aliases": [
"KPI",
"Key Performance Indicator"
],
"def": "A single measured figure that shows how well something is going against a goal.",
"example": "Waste percentage on the Canteen Insights dashboard, calculated as items thrown out divided by items put out for sale.",
"link": true
},
{
"id": "term-knowledge-base",
"name": "Knowledge Base",
"aliases": [
"Knowledge Base"
],
"def": "The part of an expert system that stores facts and IF–THEN rules about a specific topic.",
"example": "The eight watering and sun-stress rules in a plant-care advisor.",
"link": true
},
{
"id": "term-latency",
"name": "Latency",
"aliases": [
"Latency"
],
"def": "The time a signal takes to travel from sender to receiver, usually measured in milliseconds.",
"example": "A geostationary satellite link has noticeably higher latency than a fibre connection.",
"link": true
},
{
"id": "term-least-privilege",
"name": "Least Privilege",
"aliases": [
"Least Privilege"
],
"def": "The principle that users and programs receive only the minimum access needed to do their job.",
"example": "A receptionist can read appointments but cannot open clinical notes.",
"link": true
},
{
"id": "term-level-0-dfd",
"name": "Level 0 Data Flow Diagram",
"aliases": [
"Level 0 DFD",
"Level 0 Data Flow Diagram",
"context diagram"
],
"def": "An overview (context) data flow diagram that shows the whole system as one process with its external entities, and no data stores or internal processes.",
"example": "A canteen ordering system drawn as one circle between Student and Canteen manager.",
"link": true
},
{
"id": "term-levels-of-measurement",
"name": "Levels of Measurement",
"aliases": [
"Levels of Measurement"
],
"def": "The four scales that describe how much information a variable carries: nominal (names), ordinal (order), interval (equal gaps) and ratio (equal gaps and a true zero).",
"example": "Station name is nominal, a 1 to 5 star rating is ordinal, temperature in degrees Celsius is interval and trip minutes are ratio.",
"link": true
},
{
"id": "term-live-data",
"name": "Live Data",
"aliases": [
"Live Data"
],
"def": "Real data from an organisation's actual operation that is used when testing a system.",
"example": "Last term's real canteen orders loaded into a new ordering system.",
"link": true
},
{
"id": "term-lookup-function",
"name": "LOOKUP Function",
"aliases": [
"LOOKUP Function"
],
"def": "A spreadsheet function that finds a value in one range and returns the matching value from another range.",
"example": "=LOOKUP(B2,Items!$A$2:$A$13,Items!$D$2:$D$13) returns the price of the item whose ID is in B2.",
"link": true
},
{
"id": "term-lossless-compression",
"name": "Lossless Compression",
"aliases": [
"Lossless Compression"
],
"def": "A type of compression algorithm that retains sufficient information to allow the original data to be perfectly reconstructed from the compressed data. It is used when it is important for the original data to be accurately preserved, e.g. in text documents, programming source code, application files or for archival purposes.",
"example": "A PNG screenshot or a FLAC audio file.",
"link": true
},
{
"id": "term-lossy-compression",
"name": "Lossy Compression",
"aliases": [
"Lossy Compression"
],
"def": "A type of compression algorithm that compresses data by discarding information that is not necessary to reproduce the original data with sufficient detail for the user not to notice the difference. It is used primarily for reducing the size of multimedia assets such as video, audio and photographs, especially when streaming or transmitting the data over the internet.",
"example": "An MP3 or a JPEG at low quality that shows blocky artefacts.",
"link": true
},
{
"id": "term-maintenance-documentation",
"name": "Maintenance Documentation",
"aliases": [
"Maintenance Documentation"
],
"def": "Technical information for the people who look after a system, covering its design, configuration, backup and update procedures and a log of changes.",
"example": "A guide that shows a committee member how to restore last night's backup.",
"link": true
},
{
"id": "term-malware",
"name": "Malware",
"aliases": [
"Malware"
],
"def": "Malicious software designed to interfere with the regular operation of a computer system. Often used to gain access to computers, it is usually hidden in other software to avoid user detection.",
"example": "A \"free\" game download that secretly installs software to steal passwords.",
"link": true
},
{
"id": "term-mmog",
"name": "Massive Multiplayer Online Game (MMOG)",
"aliases": [
"MMOG",
"Massive Multiplayer Online Game"
],
"def": "An online game in which very large numbers of players share one persistent world.",
"example": "Guilds of players completing a shared quest in a persistent online world.",
"link": true
},
{
"id": "term-mooc",
"name": "Massive Open Online Course (MOOC)",
"aliases": [
"MOOC",
"Massive Open Online Course"
],
"def": "An online course open to very large numbers of learners, often free to start.",
"example": "A free university course delivered by video, quizzes and forums.",
"link": true
},
{
"id": "term-mean-absolute-error",
"name": "Mean Absolute Error",
"aliases": [
"Mean Absolute Error"
],
"def": "The average size of the differences between proposed and actual values, ignoring whether they are above or below.",
"example": "Absolute errors of 75 units over eight weeks give a mean absolute error of about 9.4 units.",
"link": true
},
{
"id": "term-measure",
"name": "Measure",
"aliases": [
"Measure"
],
"def": "The numeric value analysed in each cell of a data cube.",
"example": "Sales in dollars or number of units sold.",
"link": false
},
{
"id": "term-metadata",
"name": "Metadata",
"aliases": [
"Metadata"
],
"def": "A set of data that describes and gives information about other data. For example, the metadata of a photograph is the set of data providing information about copyright.",
"example": "A photo's file details, such as when and where it was taken and its copyright.",
"link": true
},
{
"id": "term-microcontroller",
"name": "Microcontroller",
"aliases": [
"Microcontroller"
],
"def": "A small computer built for the purpose of dealing with specific tasks, such as managing the engine in a car, displaying information in a microwave control panel or receiving information from a television remote control. Microcontrollers process data inputted by users (e.g. keypad) or sensors (e.g. light).",
"example": "The chip in a microwave that reads the keypad and controls the timer and heater.",
"link": true
},
{
"id": "term-milestone",
"name": "Milestone",
"aliases": [
"Milestone"
],
"def": "An important point in a project that marks the completion of a phase or an approval. On a Gantt chart it is drawn as a hollow diamond and has no duration.",
"example": "The milestone \"Requirements approved\" is reached when the club committee signs off the needs list.",
"link": true
},
{
"id": "term-minimum-viable-product",
"name": "Minimum Viable Product",
"aliases": [
"MVP",
"Minimum Viable Product"
],
"def": "The simplest version of a product that solves the core problem and can be tested with real users.",
"example": "A start-up releases a booking page for one club before adding payments or reports.",
"link": true
},
{
"id": "term-model",
"name": "Model",
"aliases": [
"Model"
],
"def": "A mathematical, conceptual or physical representation that describes, simplifies, clarifies or provides an explanation of the structure, workings or relationships within an object, system or idea. Models can provide a means of testing and predicting behaviour within limited conditions. Models may be physical or exist in digital form.",
"example": "A spreadsheet that predicts next month’s canteen sales from past sales and the weather forecast.",
"link": false
},
{
"id": "term-moscow",
"name": "MoSCoW Prioritisation",
"aliases": [
"MoSCoW Prioritisation"
],
"def": "A common technique that sorts requirements into Must have, Should have, Could have and Won't have (this time).",
"example": "Ordering canteen app features so online ordering is a Must and loyalty points a Could.",
"link": true
},
{
"id": "term-moving-average",
"name": "Moving Average",
"aliases": [
"Moving Average"
],
"def": "A series of averages of consecutive values, used to smooth short-term variation so that the trend shows.",
"example": "A 3-month average of monthly orders.",
"link": true
},
{
"id": "term-mqtt",
"name": "MQTT",
"aliases": [
"MQTT"
],
"def": "A lightweight publish/subscribe messaging protocol in which devices publish to topics on a broker and others subscribe to those topics.",
"example": "A sensor publishes to farm/paddock3/soil/moisture and an irrigation controller subscribes.",
"link": true
},
{
"id": "term-mfa",
"name": "Multi-Factor Authentication",
"aliases": [
"2FA",
"MFA",
"Multi-Factor Authentication",
"two-factor authentication"
],
"def": "Verifying identity with two or more different types of proof: something you know, have or are.",
"example": "A password plus a code from an authenticator app.",
"link": true
},
{
"id": "term-network-diagram",
"name": "Network Diagram",
"aliases": [
"Network Diagram"
],
"def": "A diagram, also called a network map, that documents a network using labelled symbols for the devices (nodes) and lines for how they are connected.",
"example": "A router joined to the internet, two hubs and several labelled computers.",
"link": true
},
{
"id": "term-node",
"name": "Node",
"aliases": [
"Node"
],
"def": "A point in a network or graph, such as a person, a device or a category, drawn as a circle. Also called a vertex.",
"example": "In a social network graph each person is a node; in a network diagram each router or computer is a node.",
"link": false
},
{
"id": "term-non-functional-requirement",
"name": "Non-functional Requirement",
"aliases": [
"Non-functional Requirement"
],
"def": "A statement of a quality a system must have, such as speed, accessibility, privacy or reliability.",
"example": "Every panel recalculates after a filter change without a noticeable delay.",
"link": true
},
{
"id": "term-normalisation",
"name": "Normalisation",
"aliases": [
"Normalisation"
],
"def": "A relational database design process that minimises data duplication by separating data into smaller linked tables whose fields depend solely on each table's primary key.",
"example": "Moving publisher names out of a Games table into a Publishers table.",
"link": true
},
{
"id": "term-notifiable-data-breach",
"name": "Notifiable Data Breach",
"aliases": [
"NDB",
"NDB scheme",
"Notifiable Data Breach",
"eligible data breach"
],
"def": "A breach involving personal information that is likely to result in serious harm (an eligible data breach). Under the Privacy Act it must be reported to the OAIC and to the people affected.",
"example": "A misdirected spreadsheet of customers' identity documents that cannot be recovered.",
"link": true
},
{
"id": "term-nudging",
"name": "Nudging (Guided Choice)",
"aliases": [
"Guided Choice",
"Nudging",
"nudge",
"nudge theory",
"nudges"
],
"def": "A design choice that steers people towards an option without removing other options.",
"example": "A \"Most popular\" badge on one product or a pre-selected delivery option.",
"link": true
},
{
"id": "term-object-oriented-programming",
"name": "Object-Oriented Programming (OOP)",
"aliases": [
"OOP",
"Object-Oriented Programming"
],
"def": "A paradigm based on the concept of ‘objects’ that can contain data and code in the form of procedures. OOP language is a language based on the principles of ‘C’.",
"example": "A Student object holds a name and a year level (data) and can print a report (a procedure).",
"link": true
},
{
"id": "term-object-relational-mapping",
"name": "Object-Relational Mapping (ORM)",
"aliases": [
"ORM",
"Object-Relational Mapping"
],
"def": "A technique used in object-oriented programming to query and manipulate data from a database.",
"example": "A program reads a row of a Students table as a Student object instead of writing SQL for every query.",
"link": true
},
{
"id": "term-offshore-development",
"name": "Offshore Development",
"aliases": [
"Offshore Development"
],
"def": "Having a system built by a team in another country, either in the organisation's own overseas office or in a contracted firm.",
"example": "An Australian retailer has its online shop maintained by a development team overseas.",
"link": true
},
{
"id": "term-olap",
"name": "OLAP (Online Analytical Processing)",
"aliases": [
"OLAP",
"Online Analytical Processing"
],
"def": "A way of storing and querying data in multidimensional form so that users can summarise and explore it quickly from many angles.",
"example": "A manager views café sales by product, quarter and region, then drills from quarter to month.",
"link": true
},
{
"id": "term-oltp",
"name": "OLTP (Online Transaction Processing)",
"aliases": [
"OLTP",
"Online Transaction Processing"
],
"def": "The everyday system that records each transaction as it happens, such as a sale or a booking.",
"example": "A point-of-sale system that records each coffee sold.",
"link": true
},
{
"id": "term-ontology",
"name": "Ontology",
"aliases": [
"Ontology"
],
"def": "A formal description of the concepts in a domain and the relationships between them, used to classify items and infer inherited properties.",
"example": "A product ontology in which trail running shoe is a kind of running shoe, which is a kind of footwear.",
"link": true
},
{
"id": "term-open-systems-interconnection",
"name": "Open Systems Interconnection (OSI)",
"aliases": [
"OSI",
"Open Systems Interconnection"
],
"def": "This conceptual model standardises communications between all of the elements within an information or computer system.",
"example": "A seven-layer model that describes what happens between an application sending data and the cable or wireless signal that carries it.",
"link": true
},
{
"id": "term-operation-documentation",
"name": "Operation Documentation",
"aliases": [
"Operation Documentation"
],
"def": "Instructions for the people who use a system day to day, such as a user guide or quick-reference card.",
"example": "A laminated card showing the canteen coordinator how to record a stock count.",
"link": true
},
{
"id": "term-outlier",
"name": "Outlier",
"aliases": [
"Outlier"
],
"def": "A value that lies far from the rest of the data; it may be an error or a genuine unusual event.",
"example": "One $2,400 booking among bookings that are mostly under $110.",
"link": true
},
{
"id": "term-outsourcing",
"name": "Outsourcing",
"aliases": [
"Outsourcing"
],
"def": "Contracting an outside organisation to develop or run a system, or part of it, wherever that organisation is located.",
"example": "A council pays a software company to build its permits system to an agreed specification.",
"link": true
},
{
"id": "term-overplotting",
"name": "Overplotting",
"aliases": [
"Overplotting"
],
"def": "Marks on a chart overlapping so much that the pattern cannot be seen, common with very large datasets.",
"example": "A scatter graph of a million points that looks like a solid blob.",
"link": true
},
{
"id": "term-passive-data-collection",
"name": "Passive Data Collection",
"aliases": [
"Passive Data Collection"
],
"def": "Capturing data as a by-product of what people do, without them deliberately providing it.",
"example": "Dock sensors and GPS logs recording every bike trip.",
"link": true
},
{
"id": "term-personal-information",
"name": "Personal Information",
"aliases": [
"Personal Information"
],
"def": "Information or an opinion about an identified individual, or an individual who is reasonably identifiable.",
"example": "A customer's name, email address and delivery address.",
"link": true
},
{
"id": "term-pilot-implementation",
"name": "Pilot Implementation",
"aliases": [
"Pilot Implementation"
],
"def": "A way of introducing a new system in which a small part of the organisation, or a limited range of the work, uses it first before it is extended.",
"example": "One manager using the dashboard for hot food and fresh food for two weeks while other categories stay on the old paper method.",
"link": true
},
{
"id": "term-pivot-table",
"name": "Pivot Table",
"aliases": [
"Pivot Table"
],
"def": "A spreadsheet tool that summarises a large table by grouping and totalling its data.",
"example": "Total canteen revenue by item category.",
"link": true
},
{
"id": "term-paas",
"name": "Platform as a Service (PaaS)",
"aliases": [
"PaaS",
"Platform as a Service"
],
"def": "A cloud service in which the provider supplies the operating system, runtime and tools so developers deploy their own code without managing servers.",
"example": "Deploying a web app to a hosted platform such as Azure App Service.",
"link": true
},
{
"id": "term-predictive-analytics",
"name": "Predictive Analytics",
"aliases": [
"Predictive Analytics"
],
"def": "Using patterns in historical data, with statistical methods or machine learning, to estimate what is likely to happen.",
"example": "Forecasting Saturday's shuttle boardings from the temperature forecast.",
"link": true
},
{
"id": "term-predictive-search-string",
"name": "Predictive Search String",
"aliases": [
"Predictive Search String"
],
"def": "A suggested completion of a search query, chosen by estimating what the user is most likely to type.",
"example": "Typing how to cook and being offered how to cook rice.",
"link": true
},
{
"id": "term-price-elasticity-of-demand",
"name": "Price Elasticity of Demand",
"aliases": [
"Price Elasticity of Demand"
],
"def": "A measure of how much the quantity people buy changes when the price changes.",
"example": "A rise in the price of bottled water reduces units sold by more than the same rise in the price of a meat pie.",
"link": true
},
{
"id": "term-primary-data",
"name": "Primary Data",
"aliases": [
"Primary Data"
],
"def": "Data collected first-hand by an enterprise for its own purpose.",
"example": "A bike-share's own trip log or its rider survey.",
"link": true
},
{
"id": "term-primary-key",
"name": "Primary Key",
"aliases": [
"Primary Key"
],
"def": "A field, or combination of fields, whose value uniquely identifies each record in a table.",
"example": "StudentID in a Students table: no two students share one.",
"link": true
},
{
"id": "term-privacy-act",
"name": "Privacy Act 1988",
"aliases": [
"APP",
"Australian Privacy Principles",
"Privacy Act",
"Privacy Act 1988"
],
"def": "Australian Commonwealth law that regulates how agencies and many organisations collect, use, store and disclose personal information, through the Australian Privacy Principles.",
"example": "A medical practice must follow the Australian Privacy Principles when it stores patient records.",
"link": true
},
{
"id": "term-problem-definition",
"name": "Problem Definition",
"aliases": [
"Problem Definition"
],
"def": "A precise statement of the problem a project will solve, who is affected, its scope, its constraints and its success criteria.",
"example": "Members cannot see which courts are free, so a court is sometimes booked twice.",
"link": true
},
{
"id": "term-process-diary",
"name": "Process Diary (Log Book)",
"aliases": [
"Log Book",
"Process Diary"
],
"def": "A record of a project's progress made at regular intervals, including the date, the person, progress, tasks achieved, stumbling blocks, next approaches, reflections and resources used.",
"example": "An entry recording that a price format was fixed and how it was tested.",
"link": true
},
{
"id": "term-producing",
"name": "Producing",
"aliases": [
"Producing"
],
"def": "Actively realising (making) designed solutions, using appropriate resources and means of production.",
"example": "Building the booking system from the design, using the chosen software and following the plan.",
"link": false
},
{
"id": "term-product",
"name": "Product",
"aliases": [
"Product"
],
"def": "The tangible end results of natural, human, mechanical, manufacturing, electronic or digital production and processes.",
"example": "A finished mobile app, a printed poster or a working database.",
"link": false
},
{
"id": "term-backlog",
"name": "Product Backlog",
"aliases": [
"Product Backlog"
],
"def": "A prioritised list of the features and tasks still to be done in an agile project.",
"example": "A list with 'online payment' at the top and 'loyalty points' near the bottom.",
"link": true
},
{
"id": "term-project",
"name": "Project",
"aliases": [
"Project"
],
"def": "An individual or collaborative problem-solving activity undertaken by students that is planned to achieve an articulated aim.",
"example": "A student team plans and builds a booking system for a local netball club.",
"link": false
},
{
"id": "term-project-management",
"name": "Project Management",
"aliases": [
"Project Management"
],
"def": "The process of planning, organising, controlling resources, monitoring timelines and activities, and completing a project to achieve a goal that meets identified criteria.",
"example": "A team uses a Gantt chart and a process diary to keep a six-week booking system on schedule.",
"link": true
},
{
"id": "term-protocols",
"name": "Protocols",
"aliases": [
"Protocols"
],
"def": "A set of generally accepted standards or 'rules' that govern relationships and interactions between and within information systems. In communication systems including the internet, specific protocols allow for the successful transmission of data.",
"example": "HTTPS for secure web pages and SMTP for sending email.",
"link": false
},
{
"id": "term-prototype",
"name": "Prototype",
"aliases": [
"Prototype"
],
"def": "A trial product or model built to test an idea or process to inform further design development. Its purpose is to see if and how well the design works and is tested by users and systems analysts. A prototype can be either a physical object or exist in digital form.",
"example": "A clickable model of an ordering screen tested with five students.",
"link": true
},
{
"id": "term-prototyping-approach",
"name": "Prototyping Approach",
"aliases": [
"Prototyping Approach"
],
"def": "A development approach in which rough working versions are built, shown to the client and improved in cycles until the system meets the need.",
"example": "Building a spreadsheet, a paper storyboard, a clickable page and then a working dashboard, with feedback from the client at each step.",
"link": true
},
{
"id": "term-pseudo-random-number-generator",
"name": "Pseudo-random Number Generator",
"aliases": [
"Pseudo-random Number Generator"
],
"def": "A program that produces a sequence of numbers that looks random but is fully determined by a starting value called a seed.",
"example": "A seeded generator that makes the same eight weeks of sample canteen sales every time a page loads.",
"link": true
},
{
"id": "term-qualitative-data",
"name": "Qualitative Data",
"aliases": [
"Qualitative Data"
],
"def": "Data that describes qualities, categories or opinions, usually as words, labels, images or sounds.",
"example": "A rider's comment that a dock was jammed, or the name of a docking station.",
"link": true
},
{
"id": "term-qos",
"name": "Quality of Service (QoS)",
"aliases": [
"QoS",
"Quality of Service"
],
"def": "Rules that give priority to important or time-sensitive network traffic over less urgent traffic.",
"example": "A router that prioritises video calls over a large file download.",
"link": true
},
{
"id": "term-quantitative-data",
"name": "Quantitative Data",
"aliases": [
"Quantitative Data"
],
"def": "Data expressed as numbers that measure or count something, so arithmetic on the values is meaningful.",
"example": "Trip length in minutes and the fare in dollars for a bike-share trip.",
"link": true
},
{
"id": "term-ransomware",
"name": "Ransomware",
"aliases": [
"Ransomware"
],
"def": "Malicious software that encrypts files or locks systems and demands payment, often also threatening to publish stolen data.",
"example": "Warehouse systems locked until a ransom is paid.",
"link": true
},
{
"id": "term-regression-testing",
"name": "Regression Testing",
"aliases": [
"Regression Testing"
],
"def": "Repeating earlier tests after a change to confirm that nothing that previously worked has been broken.",
"example": "After fixing the 120-minute limit, the team also retests the 29, 30 and 120 minute cases.",
"link": true
},
{
"id": "term-relational-database",
"name": "Relational Database",
"aliases": [
"Relational Database"
],
"def": "A database that stores data in several linked tables, using primary and foreign keys, so each fact is stored once.",
"example": "Separate Riders, Bikes, Stations and Trips tables linked by RiderID, BikeID and StationID.",
"link": true
},
{
"id": "term-relative-reference",
"name": "Relative Reference",
"aliases": [
"Relative Reference"
],
"def": "A spreadsheet cell reference that changes to match its new position when the formula is copied or filled.",
"example": "Copying =D2*E2 down a column so the next row becomes =D3*E3.",
"link": true
},
{
"id": "term-requirements-traceability",
"name": "Requirements Traceability",
"aliases": [
"Requirements Traceability"
],
"def": "Linking each requirement to the design, tests and evidence that show it has been met.",
"example": "A table that lists requirement FR6 beside the tests N5, B4 to B7 and E1 to E8.",
"link": true
},
{
"id": "term-residual-risk",
"name": "Residual Risk",
"aliases": [
"Residual Risk"
],
"def": "The level of risk that remains after treatments and controls have been applied.",
"example": "Full-disk encryption reduces the risk of a lost laptop from High to Low.",
"link": true
},
{
"id": "term-risk-matrix",
"name": "Risk Matrix",
"aliases": [
"Risk Matrix"
],
"def": "A grid that rates a risk by combining its likelihood and its consequence, usually as a score with bands such as Low, Medium, High and Extreme.",
"example": "Likelihood 4 times consequence 5 gives a score of 20, rated Extreme.",
"link": true
},
{
"id": "term-risk-register",
"name": "Risk Register",
"aliases": [
"Risk Register"
],
"def": "A record of the identified risks to a project, with each risk’s likelihood, impact, response and owner.",
"example": "A register lists \"key team member unavailable\" as a high risk, with a response of pairing on critical tasks.",
"link": true
},
{
"id": "term-rbac",
"name": "Role-Based Access Control",
"aliases": [
"RBAC",
"Role-Based Access Control"
],
"def": "A method of granting permissions to roles, then assigning people to roles, instead of granting rights person by person.",
"example": "A clinic gives the Doctor role write access to clinical notes and the Receptionist role none.",
"link": true
},
{
"id": "term-roll-up",
"name": "Roll-up",
"aliases": [
"Roll-up"
],
"def": "Aggregating data up a hierarchy, or removing a dimension, to see a higher-level summary.",
"example": "Summing months into quarters and quarters into a year.",
"link": true
},
{
"id": "term-sampling-rate",
"name": "Sampling Rate",
"aliases": [
"Sampling Rate"
],
"def": "The number of times per second a sound wave is measured when it is digitised.",
"example": "CD audio uses 44,100 samples per second.",
"link": true
},
{
"id": "term-sandbox-gaming",
"name": "Sandbox Gaming",
"aliases": [
"Sandbox Gaming"
],
"def": "A virtual world where players can build their playscapes, invite other players to play and test game play.",
"example": "Building and sharing a mini-game in Minecraft.",
"link": true
},
{
"id": "term-scada",
"name": "SCADA",
"aliases": [
"SCADA"
],
"def": "Supervisory control and data acquisition: a system of sensors, controllers, networks and operator screens used to monitor and control industrial and infrastructure processes.",
"example": "A water utility monitoring reservoir levels and pump stations from a control centre.",
"link": true
},
{
"id": "term-schema",
"name": "Schema",
"aliases": [
"Schema"
],
"def": "A diagram of the organisational structure of a database showing the tables, their fields, the primary keys and the relationships between tables.",
"example": "Games, Publishers and Developers tables joined by one-to-many lines.",
"link": true
},
{
"id": "term-scope-creep",
"name": "Scope Creep",
"aliases": [
"Scope Creep"
],
"def": "The gradual addition of extra features or requirements to a project, after they were agreed, without matching changes to time, budget or resources.",
"example": "A club asks for online payments halfway through a six-week booking project.",
"link": true
},
{
"id": "term-secondary-data",
"name": "Secondary Data",
"aliases": [
"Secondary Data"
],
"def": "Data that was collected by someone else, usually for a different purpose, and is reused.",
"example": "Daily rainfall figures from the Bureau of Meteorology used to study bike demand.",
"link": true
},
{
"id": "term-semi-structured-decision",
"name": "Semi-structured Decision",
"aliases": [
"Semi-structured Decision"
],
"def": "A decision made using a specified set of finite instructions, where a person may still review or approve the result.",
"example": "A loan officer approving an exception to a risk score calculated by fixed rules.",
"link": true
},
{
"id": "term-sensor",
"name": "Sensor",
"aliases": [
"Sensor"
],
"def": "A device that detects and responds to some type of input from the physical environment.",
"example": "A temperature probe in a cold room or a motion sensor over a door.",
"link": true
},
{
"id": "term-shortest-path",
"name": "Shortest Path",
"aliases": [
"Shortest Path"
],
"def": "The route between two nodes in a weighted graph with the smallest total weight, which can be found with Dijkstra's algorithm.",
"example": "A to E across cables of 25, 20 and 10 m gives a shortest path of 55 m.",
"link": true
},
{
"id": "term-simulated-data",
"name": "Simulated Data",
"aliases": [
"Simulated Data"
],
"def": "Data made up by testers to mimic real data or to target particular cases, including boundary and invalid values.",
"example": "A test order with a price of $0.00.",
"link": true
},
{
"id": "term-slice",
"name": "Slice",
"aliases": [
"Slice"
],
"def": "An OLAP operation that fixes one dimension at a single value, leaving a smaller table.",
"example": "Slicing the sales cube at Region = Coast gives a Product by Quarter table.",
"link": false
},
{
"id": "term-slicer",
"name": "Slicer",
"aliases": [
"Slicer"
],
"def": "A set of buttons in a spreadsheet dashboard that filters connected pivot tables and charts without changing the source data.",
"example": "Clicking Riverside Park in a station slicer to show only that station's figures.",
"link": true
},
{
"id": "term-smishing",
"name": "Smishing",
"aliases": [
"Smishing"
],
"def": "Phishing carried out by SMS text message, tricking the recipient into following a link or giving information.",
"example": "A text claiming to be a toll operator with a link to a fake payment page.",
"link": true
},
{
"id": "term-social-engineering",
"name": "Social Engineering",
"aliases": [
"Social Engineering"
],
"def": "Manipulating people, rather than technology, into revealing information or giving access.",
"example": "A caller pretending to be IT support asks an employee to read out a login code.",
"link": true
},
{
"id": "term-social-network",
"name": "Social Network",
"aliases": [
"Social Network"
],
"def": "A structure that describes the relationships that exist between individuals and/or organisations. Social networking services and tools provide a mechanism for people who share common interests or personal ties to communicate, share and interact using a range of media such as text, images and video.",
"example": "A photo-sharing service, or a graph showing which students are friends with each other.",
"link": true
},
{
"id": "term-saas",
"name": "Software as a Service (SaaS)",
"aliases": [
"SaaS",
"Software as a Service"
],
"def": "A cloud service in which the provider runs a complete application that users access over the internet, usually by subscription.",
"example": "Microsoft 365 email and documents, or MYOB accounting.",
"link": true
},
{
"id": "term-sprint",
"name": "Sprint",
"aliases": [
"Sprint"
],
"def": "A short, fixed-length work cycle in Scrum, typically one to four weeks, that ends in a working increment and a review.",
"example": "A two-week sprint to build the login and timetable screens.",
"link": true
},
{
"id": "term-stakeholder",
"name": "Stakeholder",
"aliases": [
"Stakeholder"
],
"def": "A person or group who is involved in, or affected by, a project or its outcome.",
"example": "Members, the club secretary, the canteen coordinator and suppliers are stakeholders in a booking and inventory system.",
"link": true
},
{
"id": "term-stock-out",
"name": "Stock-out",
"aliases": [
"Stock-out"
],
"def": "A situation in which an item sells out and customers cannot buy it, so recorded sales understate real demand.",
"example": "Meat pies that are all sold by lunchtime on a Friday.",
"link": true
},
{
"id": "term-storyboard",
"name": "Storyboard",
"aliases": [
"Storyboard"
],
"def": "A diagram that shows the various interfaces (screens) of a product and the links between them. In NESA notation, buttons with a dot and arrow show which screen they open.",
"example": "Three linked screens for a school canteen website: Home, Prices and Specials.",
"link": true
},
{
"id": "term-stratified-sampling",
"name": "Stratified Sampling",
"aliases": [
"Stratified Sampling"
],
"def": "A sampling method that divides the population into groups (strata) and samples each group in proportion to its size.",
"example": "Surveying 20 of 200 members and 40 of 400 casual riders, so both groups are represented.",
"link": true
},
{
"id": "term-structured-data",
"name": "Structured Data",
"aliases": [
"Structured Data"
],
"def": "Data with a high degree of organisation, such that it can easily be analysed and processed using algorithms. The organisation of the data takes on a form that captures the properties and behaviours of the source the data represents.",
"example": "A table of trips with fixed fields for date, start station, end station and minutes.",
"link": true
},
{
"id": "term-structured-decision",
"name": "Structured Decision",
"aliases": [
"Structured Decision"
],
"def": "A decision that is fully specified and can be automated, so the system decides and acts without human intervention.",
"example": "A warehouse system reordering an item when stock falls below a set level.",
"link": true
},
{
"id": "term-structured-query-language",
"name": "Structured Query Language (SQL)",
"aliases": [
"SQL",
"Structured Query Language"
],
"def": "Specialist programming language used to manage data and access data in relational database management systems.",
"example": "SELECT Name FROM Games WHERE Cost > 20 ORDER BY Cost DESC",
"link": true
},
{
"id": "term-success-criteria",
"name": "Success Criteria",
"aliases": [
"Success Criteria"
],
"def": "Measurable statements, set at the start of a project, that describe what a solution must achieve to be judged successful.",
"example": "Staff can enter an order in under one minute.",
"link": true
},
{
"id": "term-supply-chain-attack",
"name": "Supply-Chain Attack",
"aliases": [
"Supply-Chain Attack"
],
"def": "An attack that compromises a supplier, software update or service that the real target trusts.",
"example": "Malicious code hidden in a software update that customers install.",
"link": true
},
{
"id": "term-surplus-data",
"name": "Surplus Data",
"aliases": [
"Surplus Data"
],
"def": "Data that is duplicated, unused, out of range or beyond the purpose of the system, and so adds cost and risk without adding value.",
"example": "A probe reading every second when only 15-minute averages and alerts are needed.",
"link": true
},
{
"id": "term-system-flowchart",
"name": "System Flowchart",
"aliases": [
"System Flowchart"
],
"def": "A diagram that represents the main processes and devices in a system, using symbols such as online input, direct access storage and cloud, with arrows showing the direction of data.",
"example": "A doctor's system where visit details are entered, stored in a consultation file and sent to the cloud.",
"link": true
},
{
"id": "term-system-implementation",
"name": "System Implementation",
"aliases": [
"System Implementation"
],
"def": "The implementation method applied when introducing a new or redesigned enterprise system. Typically methods include: direct, parallel, phased or pilot.",
"example": "A club goes live with its stock module first and its booking module three weeks later.",
"link": true
},
{
"id": "term-system-maintenance",
"name": "System Maintenance",
"aliases": [
"System Maintenance"
],
"def": "Work done after a system goes live to fix faults, adapt it to changes and improve it.",
"example": "Updating a booking system when the club adds a new membership type.",
"link": true
},
{
"id": "term-systems-thinking",
"name": "Systems Thinking",
"aliases": [
"Systems Thinking"
],
"def": "An understanding of how related objects or components interact to influence how systems function. Students are provided with opportunities to recognise the connectedness of, and interactions between phenomena, people, places and events in local and wider contexts and consider the impact of their decisions. Understanding the complexity of systems and the interdependence of components is important for scientific research and for the creation of solutions to technical, economic and social issues.",
"example": "Seeing that changing the canteen’s ordering app also affects the kitchen, the cashiers and the parents who pay.",
"link": true
},
{
"id": "term-task-float",
"name": "Task Float",
"aliases": [
"Task Float",
"float time"
],
"def": "The number of days a task can be delayed without delaying the end date of the project; also called slack. Tasks on the critical path have no float.",
"example": "A task with 2 days of float can finish 2 days late and the project still ends on time.",
"link": true
},
{
"id": "term-threat-actor",
"name": "Threat Actor",
"aliases": [
"Threat Actor"
],
"def": "An individual or group that poses a security threat to an individual or organisation.",
"example": "A criminal group running a ransomware campaign, or an employee who leaks customer data.",
"link": true
},
{
"id": "term-transmission-media",
"name": "Transmission Media",
"aliases": [
"Transmission Media"
],
"def": "The means through which data is sent from one system to another on a network.",
"example": "An Ethernet cable, an optical fibre or a Wi-Fi radio signal.",
"link": true
},
{
"id": "term-trend-line",
"name": "Trend Line",
"aliases": [
"Trend Line"
],
"def": "A line, usually the least-squares line of best fit, drawn through data to show its general direction and to make forecasts.",
"example": "A straight trend line fitted to twelve months of orders and extended one month ahead to forecast demand.",
"link": true
},
{
"id": "term-truncated-axis",
"name": "Truncated Axis",
"aliases": [
"Truncated Axis"
],
"def": "A value axis that does not start at zero, which can exaggerate differences in a column chart.",
"example": "A column axis from 90 to 95 makes 94% look four times as tall as 91%.",
"link": true
},
{
"id": "term-tpm",
"name": "Trusted Platform Module (TPM)",
"aliases": [
"TPM",
"Trusted Platform Module"
],
"def": "A dedicated security chip that stores cryptographic keys in hardware and helps verify that a device started with trusted software.",
"example": "BitLocker uses a TPM to keep a laptop's drive encryption key safe.",
"link": true
},
{
"id": "term-truth-maintenance",
"name": "Truth Maintenance",
"aliases": [
"Truth Maintenance"
],
"def": "A technique that records the reasons for each conclusion so it can be withdrawn automatically when its supporting facts change.",
"example": "Retracting overwatered when the user corrects soil_wet to dry.",
"link": true
},
{
"id": "term-unstructured-data",
"name": "Unstructured Data",
"aliases": [
"Unstructured Data"
],
"def": "Data with no predefined model or field layout, such as free text, images, audio and video.",
"example": "Rider comments, photos of damaged bikes and recorded customer calls.",
"link": true
},
{
"id": "term-unstructured-decision",
"name": "Unstructured Decision",
"aliases": [
"Unstructured Decision"
],
"def": "A decision that cannot be made by following a fixed set of instructions, so human judgement is required. The syllabus describes it as \"an infinite set of instructions where judgement may be required\".",
"example": "Deciding whether a start-up should open a second shop in another town.",
"link": true
},
{
"id": "term-user-experience",
"name": "User Experience (UX)",
"aliases": [
"UX",
"User Experience"
],
"def": "The usability, ease of use, and enjoyment provided in the interaction between the customer and the product.",
"example": "A checkout that takes three taps instead of ten.",
"link": true
},
{
"id": "term-user-interface",
"name": "User Interface (UI)",
"aliases": [
"UI",
"User Interface"
],
"def": "The means by which users interact with computer hardware or software. In software, this usually comprises fields for text and number entry, mouse pointers, buttons and other graphical elements. In hardware, switches, dials and light-emitting diodes (LEDs) provide information about the interactions between a user and a machine.",
"example": "The buttons, menus and text fields on a school canteen ordering page.",
"link": true
},
{
"id": "term-validation",
"name": "Validation",
"aliases": [
"Validation"
],
"def": "Checking that data is reasonable and allowed before it is accepted, for example by type, range, format or presence.",
"example": "A range check rejects an age of 250.",
"link": true
},
{
"id": "term-vector-graphic",
"name": "Vector Graphic",
"aliases": [
"Vector Graphic",
"vector image"
],
"def": "An image built from geometric shapes described by mathematical formulas, so it stays sharp at any size.",
"example": "A club logo saved as an SVG that prints equally well on a badge or a banner.",
"link": true
},
{
"id": "term-verification",
"name": "Verification",
"aliases": [
"Verification"
],
"def": "Checking that data has been entered or transferred correctly, such as by double entry or comparing totals with the source.",
"example": "Two staff type the same figures and the system compares them.",
"link": true
},
{
"id": "term-version-history",
"name": "Version History",
"aliases": [
"Version History"
],
"def": "A record kept by a file or collaboration tool of who changed a file and when, allowing earlier versions to be restored.",
"example": "Restoring yesterday's version of a shared design document.",
"link": true
},
{
"id": "term-virtual-reality",
"name": "Virtual Reality (VR)",
"aliases": [
"VR",
"Virtual Reality"
],
"def": "The use of computing technology to create a simulated environment. Unlike traditional user interfaces, VR places the user inside an experience. Instead of viewing a screen in front of them, users are immersed and able to interact with three-dimensional worlds.",
"example": "A headset that places you inside a 3D tour of a museum.",
"link": true
},
{
"id": "term-visualisation",
"name": "Visualisation",
"aliases": [
"Visualisation"
],
"def": "The presentation of data or information through pictures or graphics to help the intended audience understand its significance.",
"example": "A column chart that shows monthly sales so a manager can see the busy months at a glance.",
"link": false
},
{
"id": "term-volume-testing",
"name": "Volume Testing",
"aliases": [
"Volume Testing"
],
"def": "Testing how a system performs with a large amount of data or many users.",
"example": "Loading ten thousand orders to check searches stay fast.",
"link": true
},
{
"id": "term-vulnerability",
"name": "Vulnerability",
"aliases": [
"Vulnerability"
],
"def": "A weakness in data, people, processes or technology that a threat actor can exploit.",
"example": "An internet-facing server that has not been patched.",
"link": true
},
{
"id": "term-waterfall-approach",
"name": "Waterfall Approach",
"aliases": [
"Waterfall Approach",
"waterfall",
"waterfall (structured)",
"waterfall model"
],
"def": "A development approach in which the stages (requirements, design, development, testing, installation and maintenance) run in order, each completed and signed off before the next begins. The syllabus calls it waterfall (structured).",
"example": "A hospital records system with fixed regulatory requirements is developed in signed-off stages.",
"link": true
},
{
"id": "term-wcag",
"name": "Web Content Accessibility Guidelines (WCAG)",
"aliases": [
"WCAG",
"Web Content Accessibility Guidelines"
],
"def": "The W3C's internationally recognised guidelines for making web content accessible, organised under four principles: perceivable, operable, understandable and robust.",
"example": "Providing alt text for images and at least 4.5:1 contrast for body text.",
"link": true
},
{
"id": "term-webometrics",
"name": "Webometrics",
"aliases": [
"Webometrics"
],
"def": "The quantitative study of web resources, including the links between pages, their content and how they are used.",
"example": "Analysing which sites link to a page to estimate how relevant it is.",
"link": true
},
{
"id": "term-weighted-graph",
"name": "Weighted Graph",
"aliases": [
"Weighted Graph"
],
"def": "A graph in which each edge has a number, such as a distance, cost or delay.",
"example": "Cable lengths in metres on the links between five sites.",
"link": true
},
{
"id": "term-what-if-analysis",
"name": "What-if Analysis",
"aliases": [
"What-if Analysis"
],
"def": "Changing an input to a model, such as a price or a quantity, to see how the results would change.",
"example": "Lowering the number of ham salad rolls put out each day to see the projected effect on waste and sales.",
"link": true
},
{
"id": "term-wireframe",
"name": "Wireframe",
"aliases": [
"Wireframe"
],
"def": "A simple, low-fidelity layout of a screen that shows structure and placement without colour or final content.",
"example": "Grey boxes labelled Header, Image and Button on a sketch of a home page.",
"link": true
},
{
"id": "term-workflow",
"name": "Workflow",
"aliases": [
"Workflow"
],
"def": "A sequence of processes and/or activities that a document or artefact transitions through in order to reach completion.",
"example": "A leave request that moves from the employee to a manager for approval, then to payroll.",
"link": true
}
];
