/* Quiz bank for Enterprise Project (topics/enterprise-project.html).
   One entry per data-quiz key on the page: ep-1, ep-2, ep-3, ep-4, five questions each.
   Each question: { q: "…", options: ["…", "…", "…", "…"], answer: <index of the right option>, why: "…" }. */
window.HSC_QUIZZES = Object.assign(window.HSC_QUIZZES || {}, {
  // Part 1: Identifying and defining
  'ep-1': [
    { q: 'Which of these is a problem definition rather than a solution?',
      options: ['Build a mobile app for the club', 'Members cannot see which courts are free, so a court is sometimes booked twice', 'Store the bookings in a cloud database', 'Create a website with a booking form'],
      answer: 1,
      why: 'A problem definition describes the problem and who has it. The other options each name a product or technology, which is a solution.' },
    { q: 'At the end of Thursday, a five-day task that started on Monday is shown as 60% complete on a Gantt chart. Four of its five days have passed. What does this tell the project manager?',
      options: ['The task is on schedule', 'The task is ahead of schedule', 'Nothing can be concluded without the budget', 'The task is behind: 80% was expected, and tasks that depend on it may be late'],
      answer: 3,
      why: 'Four of five days is 80% of the planned time. Progress of 60% is behind plan, and dependent tasks cannot start until this one finishes.' },
    { q: 'Which statement best describes an iterative approach to a project?',
      options: ['Repeating cycles of design, build, test and review so that each pass improves the system', 'Completing each stage once, in order, and never returning to it', 'Handing the whole project to an outside organisation', 'Testing only when all development is finished'],
      answer: 0,
      why: 'Iteration means repeating a cycle and improving with feedback. Completing stages once in order describes a strict waterfall approach.' },
    { q: 'A retailer has its ordering system built by its own office in another country. Which description is correct?',
      options: ['Outsourcing but not offshore development', 'Neither outsourcing nor offshore development', 'Offshore development, but not outsourcing', 'Freelance work'],
      answer: 2,
      why: 'Offshore means the work is done in another country. Outsourcing means paying an outside organisation, and here the work stays within the company, so it is offshore but not outsourced.' },
    { q: 'A club hires a freelance developer to write its booking code. What should the agreement state so the club can change the code later?',
      options: ['The freelancer’s hourly rate', 'Who owns the code, or the club’s licence to use and modify it', 'The freelancer’s home address', 'The programming language only'],
      answer: 1,
      why: 'Under the Copyright Act 1968 the creator is generally the first owner, so ownership or a licence to modify must be agreed in writing. Rate and language do not settle this.' },
  ],
  // Part 2: Researching and planning
  'ep-2': [
    { q: 'Which of these should NOT appear on a Level 0 data flow diagram of a booking system?',
      options: ['An external entity called Member', 'A single process for the whole system', 'A data store called Bookings', 'A labelled flow called Booking request'],
      answer: 2,
      why: 'A Level 0 diagram shows one process, the external entities and the flows between them. Data stores first appear in a Level 1 diagram.' },
    { q: 'In a NESA system flowchart, which symbol shows a file that the system can read from and write to directly?',
      options: ['Paper document', 'Online display', 'Direct access storage', 'Magnetic tape'],
      answer: 2,
      why: 'A file reached directly is direct access storage, drawn as a cylinder. A double-headed arrow shows the process both reads and writes it.' },
    { q: 'A team needs to record that a booking is refused when a member’s fees are unpaid and the booking is not for a guest. Which tool records this rule most clearly?',
      options: ['A budget', 'A decision tree', 'A process diary', 'A Level 0 data flow diagram'],
      answer: 1,
      why: 'A decision tree shows how questions lead to outcomes, which suits a business rule and gives one test case per path.' },
    { q: 'The team breaks “no double bookings” into steps and writes an algorithm that compares start and end times. Which thinking skill is this?',
      options: ['Systems thinking', 'Design thinking', 'Computational thinking', 'Collaborative thinking'],
      answer: 2,
      why: 'Decomposing a problem, finding a pattern and writing an algorithm are computational thinking. Design thinking centres on users, and systems thinking on how parts connect.' },
    { q: 'A client says, “I want a reminder feature, and I want online payments as well.” The budget and time allow only one. What is the best next step?',
      options: ['Build both and run over budget', 'Refuse both', 'Build whichever is quicker without telling the client', 'Discuss needs and wants with the client, agree priorities, and record the decision'],
      answer: 3,
      why: 'Negotiating needs and wants means finding the need behind each request, showing the cost, agreeing priorities and recording the agreement, for example as a change request.' },
  ],
  // Part 3: Producing and implementing
  'ep-3': [
    { q: 'A survey asks: “Don’t you agree online booking would be much better?” What is wrong with this question?',
      options: ['It is leading: it suggests the answer wanted', 'It is an open question', 'It uses a rating scale', 'It is double-barrelled'],
      answer: 0,
      why: 'A leading question pushes people towards one answer. A better version is “How would you prefer to book a court?”.' },
    { q: 'A hospital is replacing its patient records system. Requirements are fixed by regulation and a failure could harm patients. Which development approach best fits?',
      options: ['End-user development', 'Waterfall (structured)', 'Prototyping only', 'No planned approach'],
      answer: 1,
      why: 'Clear, stable requirements and a high cost of failure suit a structured approach with signed-off stages and detailed documentation. Agile elements might still be used for parts of the interface.' },
    { q: 'A small team’s requirements are still unclear, but the client can meet them every week and wants something usable soon. Which approach fits best?',
      options: ['Waterfall', 'Outsourcing to a fixed-price contract', 'Agile, with prototyping', 'End-user development by the client'],
      answer: 2,
      why: 'Unclear requirements, an available client and early value point to short cycles with feedback and early prototypes.' },
    { q: 'A firm with five depots replaces its parcel-tracking system by switching only the Parkes depot first, then the others. Which implementation method is this?',
      options: ['Direct', 'Phased', 'Parallel', 'Pilot'],
      answer: 3,
      why: 'Introducing the complete new system in one location first is a pilot. Phased introduces one part (module) at a time for everyone.' },
    { q: 'For a risk register, a risk has likelihood Medium (2) and impact High (3). Using Low = 1, Medium = 2 and High = 3 multiplied together, what is its rating and a sensible response?',
      options: ['5, accept it', '6, high: reduce it and give it an owner', '3, medium: ignore it', '9, high: outsource the project'],
      answer: 1,
      why: '2 × 3 = 6, which is a high rating on this scale. A high risk needs a specific response, such as a way to reduce it, and a named owner who monitors it.' },
  ],
  // Part 4: Testing and evaluating
  'ep-4': [
    { q: 'Which pair correctly distinguishes verifying from validating a system?',
      options: ['Verify: check it meets the users’ real needs. Validate: check it matches the specification', 'Verify: check it was built to the specification. Validate: check it meets the users’ real needs', 'They mean the same thing', 'Verify: test it with beta users. Validate: test it with simulated data'],
      answer: 1,
      why: 'Verification asks whether the system was built correctly against its specification. Validation asks whether it is the right system for the real needs.' },
    { q: 'A booking must last from 30 to 120 minutes. Which set contains boundary test data?',
      options: ['60, 75, 90', 'abc, blank, −30', '10, 200, 500', '29, 30, 120, 121'],
      answer: 3,
      why: 'Boundary data is on and just either side of each limit: 29 and 30, 120 and 121. The abc, blank and −30 set is erroneous data, and the others are neither.' },
    { q: 'A test enters 121 minutes for the 30 to 120 rule and the system accepts it. What should the team do?',
      options: ['Change the expected result to “accepted”', 'Ignore it because 121 is unlikely', 'Log it as a fault, fix the check, and retest this and the neighbouring tests', 'Delete the test'],
      answer: 2,
      why: 'The expected result came from the requirements, so the system is wrong. Fix it, then retest and repeat nearby tests to check that nothing else broke (regression testing).' },
    { q: 'What is the best way to trial a user guide?',
      options: ['Ask the developers to read it', 'Check the spelling', 'Give it to someone who did not build the system, have them do real tasks with only the guide, and note where they struggle', 'Print it and file it'],
      answer: 2,
      why: 'A trial shows whether the guide can actually be followed. People who built the system cannot see the gaps that a new user will.' },
    { q: 'Six weeks after go-live, the club compares booking administration time and the number of double bookings with the figures recorded before implementation. What is this activity?',
      options: ['Reviewing the impact of implementation', 'Volume testing', 'Direct implementation', 'Simulated data testing'],
      answer: 0,
      why: 'Comparing after with before, against the success criteria, to see the effect on the people and organisation is an impact review. It supports evaluation.' },
  ],
});
