/* Quiz bank for the Course Toolkit (topics/toolkit.html).
   One entry per data-quiz key on the page: tk-1 to tk-5, five questions each.
   Each question: { q: "…", options: ["…", "…", "…", "…"], answer: <index of the right option>, why: "…" }. */
window.HSC_QUIZZES = Object.assign(window.HSC_QUIZZES || {}, {
  // Part 1: System and data modelling tools (Course Specifications pp.4-11)
  'tk-1': [
    { q: 'In a NESA data flow diagram, which symbol represents a data store?',
      options: ['A circle', 'A cylinder', 'A closed, near-square rectangle', 'A rectangle that is open on one side'],
      answer: 3,
      why: 'NESA draws a data store as a rectangle open on one side. A circle is a process, a closed near-square rectangle is an external entity, and a cylinder is not a NESA DFD symbol.' },
    { q: 'A diagram shows one circle labelled "Canteen ordering", two external entities (Student and Canteen manager) and four labelled flows between them. There are no data stores. What is it?',
      options: ['A Level 1 data flow diagram', 'A system flowchart', 'A Level 0 data flow diagram', 'A decision tree'],
      answer: 2,
      why: 'A Level 0 diagram gives an overview of the whole system as a single process, with its external entities, and shows no data stores or internal processes.' },
    { q: 'Staff type each order into a system that saves it to a customer file and prints a packing list. Which pair of NESA system flowchart symbols shows the typed order and the stored file?',
      options: ['Online input and direct access storage', 'Manual operation and paper document', 'Online display and cloud', 'Process and magnetic tape'],
      answer: 0,
      why: 'Data entered directly is online input, and a file that can be reached directly is direct access storage. The packing list would be a paper document.' },
    { q: 'A field holds an order number made of the letter C followed by four digits, such as C0417. Using NESA\'s format notation (X = character, N = digit), which data format describes it?',
      options: ['XXXXX', 'NNNNN', '#####.##', 'XNNNN'],
      answer: 3,
      why: 'One character followed by four digits is XNNNN. XXXXX would allow letters in every position, NNNNN would not allow the letter, and #####.## is a decimal number format.' },
    { q: 'A decision tree asks about temperature with branches ">30", "15 to 30" and "below 15". Which is a fault in the tree?',
      options: ['A branch that says "20 to 35", so a reading of 25 fits two branches', 'Each branch is labelled', 'A path ends in a final action', 'The tree is drawn with rectangles'],
      answer: 0,
      why: 'Branches from one condition must cover every value exactly once. Overlapping ranges make a reading such as 25 ambiguous. Labelled branches, final actions and rectangles are all correct practice.' },
  ],
  // Part 2: Project management tools (pp.12-13)
  'tk-2': [
    { q: 'What does a hollow diamond on a NESA Gantt chart show?',
      options: ['A task that is 100% complete', 'A milestone', 'A task allocated to a team member', 'A dependency between two tasks'],
      answer: 1,
      why: 'Important milestones are marked on the chart, and NESA draws them as hollow diamonds. A milestone is a point in time, not a task with a duration.' },
    { q: 'Task B cannot start until task A has finished. How does a Gantt chart show this?',
      options: ['Both bars start on the same day', 'Task B is drawn in a darker colour', 'An arrow joins the end of A\'s bar to the start of B\'s bar', 'A milestone is placed at the start of the chart'],
      answer: 2,
      why: 'Dependent tasks are clearly shown with an arrow from the end of the predecessor bar to the start of the dependent bar.' },
    { q: 'In NESA\'s second Gantt chart example, what does the darker part of a task\'s bar show?',
      options: ['The percentage of the task completed', 'The days still to work', 'The team member responsible', 'The weekend days'],
      answer: 0,
      why: 'The chart shows percentage completion: the darker portion is work done and the lighter portion is work remaining.' },
    { q: 'Which of these is NOT one of the things NESA says a process diary entry should include?',
      options: ['Stumbling blocks and how they were managed', 'Resources used', 'Reflective comments', 'The mark the teacher expects for the task'],
      answer: 3,
      why: 'NESA lists date, person, progress, tasks achieved, stumbling blocks, possible approaches for upcoming tasks, reflective comments and resources used. The teacher\'s expected mark is not on the list.' },
    { q: 'Halfway through a project a task is taking twice as long as estimated. What should the team do?',
      options: ['Leave the Gantt chart as originally drawn', 'Update the chart to show actual against estimated time, and record the issue in the process diary', 'Delete the task from the chart', 'Change the estimated time so the chart looks on schedule'],
      answer: 1,
      why: 'NESA says charts should be regularly updated to reflect actual versus estimated times, and the diary records stumbling blocks and how they were managed.' },
  ],
  // Part 3: Implementing and testing a system (pp.14-15)
  'tk-3': [
    { q: 'A regional hospital cannot afford to lose access to patient records while it changes systems. Which implementation method best reduces the risk?',
      options: ['Direct', 'Phased', 'Pilot in one ward only, then switch off the old system', 'Parallel'],
      answer: 3,
      why: 'Parallel keeps the old system running alongside the new one, so there is a fallback and results can be compared. It costs more and takes longer.' },
    { q: 'A retail chain installs its new point-of-sale software in one store first, then rolls it out to the other stores. Which method is this?',
      options: ['Pilot', 'Phased', 'Parallel', 'Direct'],
      answer: 0,
      why: 'A pilot introduces the whole system in one location or group first. Phased would introduce one part of the system at a time across all stores.' },
    { q: 'Testers load the new system with last term\'s real customer orders. Which type of data is this?',
      options: ['Simulated data', 'Live data', 'Boundary data', 'Invalid data'],
      answer: 1,
      why: 'Live data is real data from the organisation\'s own operation. Simulated data is made up by the testers to mimic real data or to target specific cases.' },
    { q: 'Fifty students use a near-final version of a school app for a fortnight and send feedback to the developers. Which method is this?',
      options: ['Volume testing', 'Acceptance testing', 'Functional testing', 'Beta testing'],
      answer: 3,
      why: 'Beta testing releases a near-final version to a limited group of real users outside the development team. Acceptance testing is the client checking the system against the agreed criteria.' },
    { q: 'Ten thousand records are loaded into a new system to see whether searches slow down. Which method is this?',
      options: ['Volume testing', 'Beta testing', 'Live data testing', 'Acceptance testing'],
      answer: 0,
      why: 'Volume testing checks performance under a large amount of data or many users.' },
  ],
  // Part 4: Relational databases and SQL (pp.16-17)
  'tk-4': [
    { q: 'According to NESA, what is the main purpose of normalisation?',
      options: ['To make queries run faster', 'To encrypt the data', 'To minimise data duplication by separating data into smaller linked tables', 'To store every field in a single table'],
      answer: 2,
      why: 'NESA describes normalisation as minimising data duplication by separating the database into smaller linked tables, which protects data integrity because each fact is stored once.' },
    { q: 'In NESA\'s games schema, Games has the fields ID (P), Name, Release_date, Cost, Publisher_ID (F) and Developer_ID (F). What does (F) mean?',
      options: ['The field must be a number', 'The field is a foreign key that links to another table', 'The field is the primary key', 'The field is the first in the table'],
      answer: 1,
      why: 'P marks the primary key and F marks a foreign key: a field holding the primary key value of a record in another table, which forms the link.' },
    { q: 'Which query lists the names of all games that cost more than $20, with the most expensive first?',
      options: ['SELECT Name FROM Games ORDER BY Cost DESC WHERE Cost > 20', 'SELECT Name FROM Games WHERE Cost > 20 ORDER BY Cost DESC', 'SELECT Name WHERE Cost > 20 FROM Games ORDER BY Cost', 'SELECT Cost FROM Games WHERE Name > 20 ORDER BY Cost ASC'],
      answer: 1,
      why: 'The clauses must be in the order SELECT, FROM, WHERE, ORDER BY. DESC puts the highest cost first.' },
    { q: 'Which WHERE condition correctly joins the Games and Publishers tables?',
      options: ['Games.Cost = Publishers.Name', 'Games.Name = Publishers.Publisher_ID', 'Games.Publisher_ID = Publishers.Publisher_ID', 'Games.ID = Publishers.Name'],
      answer: 2,
      why: 'A join matches a foreign key with the primary key it refers to: Publisher_ID in Games with Publisher_ID in Publishers.' },
    { q: 'The Games table has these games and costs: Outback Dash $9.99, Kelp Quest $14.95, Coral Code $12.50, Reef Runner $19.95. What does SELECT Name FROM Games WHERE Cost < 15 ORDER BY Name ASC display?',
      options: ['Outback Dash, Kelp Quest, Coral Code', 'Coral Code, Kelp Quest, Outback Dash', 'Outback Dash, Coral Code, Kelp Quest', 'Coral Code, Kelp Quest, Outback Dash, Reef Runner'],
      answer: 1,
      why: 'Three games cost less than $15 (Reef Runner does not). ORDER BY Name ASC then puts them in alphabetical order.' },
  ],
  // Part 5: Machine learning and application software (pp.18-21)
  'tk-5': [
    { q: 'What does NESA say students must know about machine learning and statistical modelling?',
      options: ['How each algorithm works, step by step', 'How to write a machine learning program', 'How to calculate a model by hand', 'That they can be used independently or together to analyse data and make predictions, without needing to know the underlying logic'],
      answer: 3,
      why: 'NESA says students should know they can be used independently or together to analyse datasets and make predictions, and be aware of real-world uses, but they are not required to understand the underlying logic.' },
    { q: 'Cell H1 holds the GST rate. E2 contains =D2*$H$1 and is filled down to E6. What does E3 contain?',
      options: ['=D3*$H$1', '=D3*$H$2', '=D2*$H$1', '=D3*H1'],
      answer: 0,
      why: 'D2 is a relative reference, so it becomes D3. $H$1 is absolute, so it stays locked on the GST rate.' },
    { q: 'A loyalty table in J2:K5 lists 0 points = 0%, 50 = 5%, 100 = 10% and 200 = 15%. What does =VLOOKUP(120,J2:K5,2,TRUE) return?',
      options: ['5%', '15%', 'An error, because 120 is not in the table', '10%'],
      answer: 3,
      why: 'With TRUE (approximate match) it finds the largest value not more than 120, which is 100, and returns its discount, 10%.' },
    { q: 'According to NESA, what should expert system software let you display?',
      options: ['Only the final conclusion', 'The rules used to reach a conclusion, in text and as a decision tree', 'A flowchart of the program\'s code', 'The training data used to teach the system'],
      answer: 1,
      why: 'NESA says an expert system should display the rules used to reach a conclusion in both a text format and as a decision tree, as well as allowing rules to be added, removed and edited.' },
    { q: 'A club needs a logo with a transparent background that stays sharp when enlarged for a banner. Which is the best choice?',
      options: ['A bitmap saved as JPEG', 'A low-resolution photograph', 'A vector graphic, for example saved as SVG', 'A screenshot saved as a bitmap'],
      answer: 2,
      why: 'Vector graphics are built from geometric shapes, so they stay sharp at any size, and SVG supports a transparent background. JPEG does not support transparency and bitmaps blur when enlarged.' },
  ],
});
