#!/usr/bin/env python3
"""Regenerate resources/Syllabus-Mapping.md: every NESA dot point → the section that covers it."""
import html as htmllib
import os, re, sys
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'scripts'))
from restructure import load_syllabus

from page_specs import SPECS

# Focus areas in course order (Year 11 then Year 12), taken from scripts/page_specs.py.
ORDER = [(spec['focus_area'], f'{slug}.html', f'Year {spec["year"]}') for slug, spec in SPECS.items()]
SITE = 'https://4bzdog.github.io/HSC_EnterpriseComputing/topics/'

syl = load_syllabus()
out = ['# NESA Syllabus Mapping', '',
       'Every content dot point in the NESA Enterprise Computing 11–12 Syllabus (2022), in NESA\'s order, with the section of these notes that covers it.',
       'Generated by `scripts/build-mapping.py` from the topic pages and `resources/nesa-syllabus-content.md`.', '']
for area, page, year in ORDER:
    html = open(os.path.join(ROOT, 'topics', page), encoding='utf-8').read()
    sections = re.findall(r'<section id="([^"]+)">\s*<h2 class="syllabus-phase">(.*?)</h2>\s*<p class="outcome-subtitle">🎯 <em>\((.*?)\)</em>', html)
    out += [f'## {year} — {area}', '']
    i = 0
    for sub, points in syl[area]:
        out += [f'### {sub}', '', '| Dot point | Section | Outcomes |', '|---|---|---|']
        for pt in points:
            sid, title, oc = sections[i]; i += 1
            title = htmllib.unescape(title)
            out.append(f'| {pt["text"]} | [{title}]({SITE}{page}#{sid}) | {oc} |')
        out.append('')
open(os.path.join(ROOT, 'resources', 'Syllabus-Mapping.md'), 'w', encoding='utf-8').write('\n'.join(out))
print('ok')
